### ISSUE TITLE
Settings not saving

### ISSUE THREAD

**Issue by geminiibaby** [Annosz/UIInfoSuite2#100]
I'm having a issue where, upon closing the game, the settings don't save when opening again. I'll have to fix them everytime. Is this a lil issue anyone else is having, or is it just on my end?

**Comment by Annosz** [comment]
This seems to be an issue that multiple users are reporting (#78 and #85), and definitely the biggest problem with the mod right now. Top priority on my list right now, but most likely will require to rewrite the saving of the settings, so it takes a while :(

**Comment by geminiibaby** [comment]
100% understandable & I apologize for missing it previously on the issues page! I typically can only focus on 1 thing at once & once I need to do something, I have to do it, & only that, so I don't forget lol. So I sometimes miss things (like how some already reported it) while doing the same exact thing as others if this makes sense lol. BUT.

Like I said, totally understandable & it's absolutely tolerable to fix the settings and no big deal, I wanted to say it just to (try) and help! Take care of yourself above all else & we appreciate you for all you do <3

**Comment by Annosz** [comment]
I tried to do some changing with the saving of the options, but as I never experienced the issue myself, I can't really say if it's working or not... Would you mind to do some testing? I share the new version here, and if you find that it works correctly, I will make a new release from it:

[UIInfoSuite2.zip](https://github.com/Annosz/UIInfoSuite2/files/7697666/UIInfoSuite2.zip)

**Comment by Larandar** [comment]
I was experiencing the same issue and the patched version does fix it 🚀
