### ISSUE TITLE
'UIInfoSuite2.dll' doesn't exist.

### ISSUE THREAD

**Issue by funggen** [Annosz/UIInfoSuite2#103]
the mod won`t work as smapi keep notify it doesn`t exist

**Comment by Annosz** [comment]
That's strange. UIInfoSuite2.dll is part of the zip file you downloaded. Did you copy every file to the mods directory (including that one)?

**Comment by SteffenSambhi** [comment]
I have the same issue, I cant see the UIInfoSuite2.dll file anywhere

**Comment by spon-k** [comment]
Hi all, I had the same issue momentarily. Did you download a zip of the master or of the current release? Trying to install the master file gave me that issue, but the actual release did not.

**Comment by SteffenSambhi** [comment]
Yeah I was using the  master file, where did you find the actual release?

**Comment by Annosz** [comment]
There is a [releases link](https://github.com/Annosz/UIInfoSuite2/releases) on the main page of the mod.

![image](https://user-images.githubusercontent.com/10620868/144982287-ddac5072-fc79-4a31-b844-d035d3c9d231.png)

By master file do you mean you simply downloaded the code for the mod (like you clicked Code > Download ZIP)? Sadly I can't turn that off, and I can believe that it is indeed confusing... I will update the main page to start with download instructions, hopefully that will help for new GitHub users.

**Comment by funggen** [comment]
> That's strange. UIInfoSuite2.dll is part of the zip file you downloaded. Did you copy every file to the mods directory (including that one)?



> There is a [releases link](https://github.com/Annosz/UIInfoSuite2/releases) on the main page of the mod.
> 
> ![image](https://user-images.githubusercontent.com/10620868/144982617-3e0dd83a-dfef-4721-b150-2843ad36458f.png)
> 
> By master file do you mean you simply downloaded the code for the mod (like you clicked Code > Download ZIP)? Sadly I can't turn that off, and I can believe that it is indeed confusing... I will update the main page to start with download instructions, hopefully that will help for new GitHub users.

thanks for the responds, i will try it from the release link. indeed it`s the first mod i got from github. and i did downloaded it by simply use the download zip. function.  
edit: i tried it from the release link and suffice to say that it works wonderfully. yeah, i am a bit embarassed for posting this issue now. but thank you very much.

**Comment by Annosz** [comment]
No, don't worry, if it's not intuitive how to make it work, that's a problem :) I will reopen the issue so I will remember to update the main page with instructions, so it will be easier to find.

**Comment by Eheeems** [comment]
> Hi all, I had the same issue momentarily. Did you download a zip of the master or of the current release? Trying to install the master file gave me that issue, but the actual release did not.

Thank you!
