### ISSUE TITLE
UI issues/not  saving configs

### ISSUE THREAD

**Issue by tiekanashiro** [Annosz/UIInfoSuite2#105]
Hi, so first of all I really love this mod,thanks for updating it. But I'm currently having two different issues. First  is the UI where the icons sometimes get hidden  under the tasks button [like this](https://imgur.com/WHlto7z)

Secondly since I updated the configs I choose are not saved. Everytime I load my game I have to reconnfigure the mod because it goes back to the default settings.

Also it would be awesome if you could add a toggle hotkey for the ranges, as well as range viewing for bombs like in [Range Highlight](https://www.nexusmods.com/stardewvalley/mods/6752)

They are not very big issues but I'd love to see them fixed.
Thanks again for your service!

**Comment by abrezovsky** [comment]
I am seeing the same issues myself. Using the latest version of the game, mod, and SMAPI.

**Comment by xChesirex** [comment]
It's been going on for a while, am still having the issues, have been since October

**Comment by Larandar** [comment]
Duplicated of #78 and #100
