### ISSUE TITLE
Option changes don't save

### ISSUE THREAD

**Issue by erasels** [Annosz/UIInfoSuite2#117]
Changing an option, either in-game or by changing the config.json gets reset when the game is started.

Making a change in the in-game options menu works until you reload. 

This only affects this mod.

**Comment by Annosz** [comment]
Yeah, sorry, already fixed it I just haven't had time with the holidays to zip up a new version of the mod and release it. Will do it in the next days!

**Comment by Annosz** [comment]
I published the new version with the fix, hopefully the problem will be gone forever!
