### ISSUE TITLE
Publish to Nexus

### ISSUE THREAD

**Issue by chrisheib** [Annosz/UIInfoSuite2#119]
Hey there, 
I am looking to manage all my mods with Vortex and Nexus mods so its easier for my friends to install, update und play modpacks together.
Currently afaik this version of the info suite can't be found there. 
Do you have any plans to publish it there?
If you would be okey with it I could upload and maintain the latest version there, making you the project owner if you want. In a similar spirit to #52 of course respecting Cdaragorn if he decides to come back.

**Comment by Annosz** [comment]
Looking into the possibilities on #292
