### ISSUE TITLE
Add Ukrainian language

### ISSUE THREAD

**Issue by ChulkyBow** [Annosz/UIInfoSuite2#121]
Could Ukrainian translation be added to UIInfoSuite2 mod? 

P.S : Yes, there is already a Ukrainian Mod for Stardew Valley 1.5.5+, which adds a new custom language to the game (obviously it's Ukrainian). Ukrainian mod for SDV :  https://www.nexusmods.com/stardewvalley/mods/8427
[UIInfoSuite2 - Ukrainian.zip](https://github.com/Annosz/UIInfoSuite2/files/7802808/UIInfoSuite2.-.Ukrainian.zip)

**Comment by Annosz** [comment]
Thank you! I will try to create a release on the weekend and include the new language.
