### ISSUE TITLE
Some missing icons

### ISSUE THREAD

**Issue by andres-gr** [Annosz/UIInfoSuite2#122]
Hey there, first off huge thanks to you for continuing this mod.

I am having an issue with some icons just not showing up anymore for me.

The icons that don't show are the Robin building and new recipe ones. Both of them are set to `true`.

**Comment by Annosz** [comment]
Hi @andres-gr! Sorry, I just got around to look at this issue. 
Is it still happening for you? I was not able to reproduce it, could you please send me a save file to iamannosz@gmail.com where the bug can be seen?

**Comment by auflint** [comment]
+1
Am able to reproduce. I am playing 10 Fall Year 1 with the newest berry release. There is an empty space where Robin should be, but when I hover I can still see the proper tooltip. Will attempt to attach my SMAPI log and a screenshot.
P.S. thank you for everything you do, I could not play Stardew without your work <3 

![stdw](https://user-images.githubusercontent.com/22227724/173991050-50294def-b0f0-4037-bf9c-09d44ae79257.png)
[SMAPI-latest.txt](https://github.com/Annosz/UIInfoSuite2/files/8915650/SMAPI-latest.txt)
