### ISSUE TITLE
Icon dislocation

### ISSUE THREAD

**Issue by PikachuPiPiPi** [Annosz/UIInfoSuite2#128]
![QQ截图20220122174459](https://user-images.githubusercontent.com/88024241/150633521-5a2880e0-99a6-48c4-9370-cfbe70854627.png)
When there are only special orders or Mr. Qi's special orders in the task list, but there are no help wanted queries or story queries, the icon dislocation problem as shown in the figure will occur(occurs when the task list is opened).

**Comment by Annosz** [comment]
Fixed in the new release.
