### ISSUE TITLE
Spring seeds mislabelling.

### ISSUE THREAD

**Issue by teaforjurgen** [Annosz/UIInfoSuite2#130]
When hovering over planted Spring seeds, the mod always seems to label them as Wild Horseradish. Although this doesn't force all Spring seeds products to only become Wild Horseradish. It's just a small mislabelling bug. I'm not sure if this applies to to other crafted season seeds like Winter seed, but it seems like they should be checked as well.

**Comment by Annosz** [comment]
The fix is ready and will be part of the 2.2.6 version, thanks to @tqdv!
