### ISSUE TITLE
[REQUEST] Custom community centre bundle support?

### ISSUE THREAD

**Issue by Kaitlyn-S** [Annosz/UIInfoSuite2#138]
Hi, thank you for keeping this mod up to date. I've started a save with the Community Kitchen mod by bblueberry on Nexus and I wondered if it would be possible to use the Custom Community Centre mod to hook in some compatibility with this? If not all good!

**Comment by tqdv** [comment]
Closing this as it should be implemented in UI Info Suite version 2.2.6.
