### ISSUE TITLE
[Bug] Clicking the UI Info Suite in the settings when trying to remap a control softlocks the game

### ISSUE THREAD

**Issue by Zamiell** [Annosz/UIInfoSuite2#14]
I'm copying this issue from the parent repository: https://github.com/cdaragorn/Ui-Info-Suite/issues/32

Please close if this is fixed already; I have not been able to test the new version yet.

**Comment by Annosz** [comment]
Fixed in [this ](https://github.com/Annosz/UIInfoSuite2/commit/971b67ed426c73e81847561801f5409956989959)commit.
