### ISSUE TITLE
Does not seem to be compatible?

### ISSUE THREAD

**Issue by maryanne-n** [Annosz/UIInfoSuite2#140]
Hi, I really love the UI Info Suite 2! However I am getting the "no longer compatible" error when I try to run SV and am told to check for a newer version. I am running SMAPI 3.13.4 with SV 1.5.6 on Windows 10.

**Comment by Annosz** [comment]
Hi! So far I haven't been able to reproduce the issue. I've updated to the same version as you, and for me everything looks good in SMAPI:

```
[SMAPI] SMAPI 3.13.4 with Stardew Valley 1.5.6 (build 22018) on Microsoft Windows 10 Pro
...
Loaded 21 mods:
...
[SMAPI]    UI Info Suite 2 2.2.1 by Annosz | Adds a useful information to the user interface. Based on Cdaragorn's excellent UI Info Suite.
```

Could you send a [SMAPI log](https://smapi.io/log) to help debugging?

**Comment by maryanne-n** [comment]
Hey @Annosz, totally sorry I'm just coming back with this. I see in your logs it says UI Info Suite 2 2.2.1 but for some reason the release I have (posted 16 days ago) says it's 2.0.0.  Here's the log. Apologies in advance if I downloaded the wrong release but I can't appear to find the correct version?
[SMAPI-latest.txt](https://github.com/Annosz/UIInfoSuite2/files/8083914/SMAPI-latest.txt)

**Comment by maryanne-n** [comment]
Hi @Annosz, that is exactly where I downloaded the latest release from. Is this the correct [link](https://github.com/Annosz/UIInfoSuite2/releases/download/2.2.1/UIInfoSuite2.zip)? I am getting the exact same error.

**Comment by Annosz** [comment]
HI, that is the correct place. One other thing I can think about is that you downloaded it, but you did not delete the other version from the Mods folder. The SMAPI log writes that it's still there: _UI Info Suite (from Mods\UI Info Suite\UIInfoSuite.dll)_, maybe it somehow overwrites the new version.

**Comment by maryanne-n** [comment]
...ok that seems to have fixed things. Thanks a million!! :)
