### ISSUE TITLE
Not found in GMCM

### ISSUE THREAD

**Issue by JokerBTA** [Annosz/UIInfoSuite2#142]
For some reason I am unable to change the settings for UI Info Suite 2 in GMCM. I remember it being there in previous versions but it's not there now

**Comment by DefaultLP** [comment]
It's not found in the GMCM window. It has its own Tab in the normal menu.
If it's not there, then it's probably disabled in the config.json file.
![Annotation 2022-02-13 122419](https://user-images.githubusercontent.com/29122114/153750885-8e6fafae-022f-4996-80b2-f73d102b046a.png)
![Annotation 2022-02-13 123023](https://user-images.githubusercontent.com/29122114/153750978-ff3b3ecc-1568-4651-817a-ac9dd78a0d95.png)

**Comment by JokerBTA** [comment]
Ok, I forgot about that! It's been a little while since I last played. I'll go ahead and close it

**Comment by Annosz** [comment]
Hi! I just also want to add, that you are not remembering wrong, the settings were also available in the GMCM too in an earlier version. 
However, those were supposed to be the default settings (the values used when you generate a new character), and unfortunately they had some issues with the saving of the settings, so I finally decided to remove them, and have the ApplyDefaultSettingsFromThisSave field to be able to set the default settings.

**Comment by JokerBTA** [comment]
That's what I thought! No worries! I remember the issues in previous versions!
