### ISSUE TITLE
Bundles info on item hover

### ISSUE THREAD

**Issue by Aulberon** [Annosz/UIInfoSuite2#143]
The bundle information shown when hovering over an item is inconsistent and is not compatible with remixed bundles. It shows for some items but others are simply ignored.
Apparently the way the mod checks if an item is part of a bundle isn't dynamic, it's just checking if it's part of a certain file.
It would be better to check the information directly from the save that the player is using, so that it supports not only remixed bundles, but also custom ones.

As a suggestion, you can take a look at the mod [BundleTooltips](https://github.com/musbah/StardewValleyMods/tree/master/BundleTooltips) to see how it handles this subject, as it works perfectly in every way.

**Comment by tqdv** [comment]
Does this still happen? It might've been fixed since version 2.0.1 which includes this change: 0332d990c867871fba872384f0f31c584f812545.  
I tested it a bit on my end, and remixed bundle items are marked correctly.

**Comment by Annosz** [comment]
I hope that now in the 2.2.6 version @tqdv's fix is included (#206) for the same topic, this issue does not persist. I will close this now because of the lack of responses, but if needed, please open an other bug.
