### ISSUE TITLE
[Request] Support for modded crops and other stuff

### ISSUE THREAD

**Issue by Jczion** [Annosz/UIInfoSuite2#145]
Is there any way to get more support for modded items, for instance the Harvest price? Thanks!
![image](https://user-images.githubusercontent.com/31045928/155674565-8c23c09b-528e-4a2b-82e0-9f712cf90525.png)
![image](https://user-images.githubusercontent.com/31045928/155674784-8bb4af24-ba46-4736-91e7-3c42960b2b9e.png)

**Comment by MattPlays** [comment]
@Jczion I think either myself(Im not a maintainer, I just have a lot of free time) or @Annosz would be willing to support other mods with modded crops if the mod had an API that referenced crop names and their prices/harvest price.
