### ISSUE TITLE
Compatibility with Patch 1.5

### ISSUE THREAD

**Issue by Zamiell** [Annosz/UIInfoSuite2#15]
Annosz,

The patch for 1.5 came out today and it broke this mod.
Do you have plans to update this to make it work again?
Many of us desperately need the functionality of this mod, and it's unclear if cdaragorn will fix it.

**Comment by megamegax** [comment]
There is a PR in the original repo (https://github.com/cdaragorn/Ui-Info-Suite/pull/56) for 1.5 compatibility

**Comment by Annosz** [comment]
I have checked and I find that my current version is working with game version 1.5

I uploaded a [release to this repository](https://github.com/Annosz/UIInfoSuite2/releases/tag/2.0.0) which can be used while [cdaragon#56](https://github.com/cdaragorn/Ui-Info-Suite/pull/56) is not merged. If you find any issue with it, please open an issue for it :)
