### ISSUE TITLE
No dll file in download?

### ISSUE THREAD

**Issue by erikreis29** [Annosz/UIInfoSuite2#152]
I'm not seeing a dll file for the mod in the download recommended or anywhere else in the git repo, is there a reason it is not supplied? The mod is not running for me without it, and from what I understand a dll file is required for every stardewvalley mod.

**Comment by Annosz** [comment]
Hi! I think you have not downloaded it from the correct place. On the main page there is a "[If you are here to install the mod](https://github.com/Annosz/UIInfoSuite2)" section, where it describes how to do it.

The main point is that you have to download it from the [Releases page](https://github.com/Annosz/UIInfoSuite2/releases).

**Comment by erikreis29** [comment]
You're right, don't know how I messed it up so bad since I thought I was certain I followed the process correctly the first time. My mistake and thank you for the help!
