### ISSUE TITLE
Override key bindings

### ISSUE THREAD

**Issue by sonicolasj** [Annosz/UIInfoSuite2#156]
Hi!

I use an alternate keyboard layout, so I manually rebind-ed most of SDV's keybinds. Some of the mod's bindings conflict with my bindings, such as (B)irthday overrides my "Open inventory", which is very annoying!

Is there any way to change UI Info Suite's key bindings?
If not, I'm interested in contributing!

**Comment by Annosz** [comment]
Hi!

The feature is already implemented and will be in the next release :) You will be able to set the key bindings in the ModConfig file.
I will try my best to release the new version this week as it already has a couple of bugfixes implemented.

**Comment by Annosz** [comment]
I've added it to version 2.2.2 :)
