### ISSUE TITLE
Zip not working

### ISSUE THREAD

**Issue by gabbyzza** [Annosz/UIInfoSuite2#158]
For some reason, UI Info Suite has not worked in my game ever since Nexusmods' version stopped working. I've tried downloading your file since the get-go and still no success to this day. It always gave the red code saying it is no longer compatible and needs to be updated.  However, I just attempted again with your newest file and the red code is now gone but it's now not showing UI Info Suite in my list of mods at all when the game loads...even though I am positive it is in my Mods folder. My other 30 mods are working properly so I know I'm installing it correctly. Everything is up to date that could possibly need to be. I've just become so flabbergasted as to why it won't work for me and I love this mod. Any advice would be greatly appreciated!

**Comment by Annosz** [comment]
Hello! My first question is that you deleted the original UI Info Suite and only have UI Info Suite 2 installed, right? You should not see messages from the original version, every message should contain the 2nd one.
The two mods have mostly the same code, so it is likely to break if you want to load the two versions together.

**Comment by gabbyzza** [comment]
Good morning. Yes, I made sure to delete the old file that wasn't working each and every time that I reattempted the install. Before you released this newest file, I removed the files completely since it wasn't working and even though the file was no longer in my folders whatsoever, it was still showing the red error code in my SMAPI when my game loaded up.

**Comment by Annosz** [comment]
Can you send me a [SMAPI log](https://smapi.io/log) from a game start where you experience the issue?

**Comment by gabbyzza** [comment]
https://smapi.io/log/7388c1ac0f084f7b916a54a8a0e5575b

**Comment by gabbyzza** [comment]
![2022-04-12](https://user-images.githubusercontent.com/103465542/163053193-1ca2a8db-c95a-42a7-8c85-6e74a04f3a19.png)


Also, here's a screenshot of my Mods folder showing that the mod indeed is installed although it's not showing in the SMAPI log.

**Comment by Annosz** [comment]
The screenshot shows a folder from your desktop, but Stardew Valley is set up to read the mods from C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods. Maybe you only copied the mod to this temporary folder/set up the folder on the Quick access bar incorrectly?

**Comment by gabbyzza** [comment]
wow. yup. that was it. thank you.
