### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by maozuqing** [Annosz/UIInfoSuite2#161]
https://smapi.io/log/780c4a39299f42dfb00050d77cacc504

**Comment by Annosz** [comment]
Is this character name Mia coming from a mod? From which one?

**Comment by maozuqing** [comment]
I don't know. I was still testing this morning and didn't solve this problem, so I installed the previous version and he didn't make any mistakes. But now, I have installed the latest version, and there are no errors. So I don't know what caused this problem

**Comment by Gerotama** [comment]
its from ARV https://www.nexusmods.com/stardewvalley/mods/9999?tab=description Mia is antisocial cant gift her..

**Comment by maozuqing** [comment]
OK, thank you for your help

**Comment by Annosz** [comment]
I think this issue was also resolved in version 2.2.5, with #177, just was not assigned correctly.
I will close it now.
