### ISSUE TITLE
ShowAnimalsNeedPets doesn't seem to work when the pet is indoors.

### ISSUE THREAD

**Issue by kumarchandresh** [Annosz/UIInfoSuite2#162]
The title says it all. I've included screenshots to compare it with [Better Ranching](https://www.nexusmods.com/stardewvalley/mods/859), but the behavior doesn't change when tested alone.

## Outdoors
![20220416022428_1](https://user-images.githubusercontent.com/12244518/163633633-a5ac9dd2-480b-4f42-9493-a139668903c5.jpg)

## Indoors
![20220416021957_1](https://user-images.githubusercontent.com/12244518/163633949-37ba4f62-ddb7-493a-9239-dddbcafc2afd.jpg)

**Comment by Annosz** [comment]
The fix will be available in the 2.2.6 version, thanks to @tqdv.
