### ISSUE TITLE
Queen of Sauce icon doesn't hide after watching TV

### ISSUE THREAD

**Issue by dobasy** [Annosz/UIInfoSuite2#165]
Since recent updates, Queen of Sauce icon doesn't hide after watching TV. Also, while watching TV, the dialogue says "{0}のレシピはすでに知っている。(You already know how to cook {0}.)".

I'm not sure, but I suspect both `Game1.player.cookingRecipes.Remove(_todaysRecipe)` and `Game1.player.knowsRecipe(_todaysRecipe)` requires _todaysRecipe to be in English.

And I don't think this is relevant, but doesn't `CheckForNewRecipe` run twice on the first day after a save load?

**Comment by tqdv** [comment]
I think that if this code:
https://github.com/Annosz/UIInfoSuite2/blob/29a67b630985234de979d80843e8394831cb570f/UIInfoSuite2/UIElements/ShowQueenOfSauceIcon.cs#L161-L163

is changed to:
```cs
_recipesByDescription[values[1]] = values[0];
```

then it should be fixed.

**Comment by Annosz** [comment]
The fix will be available in the 2.2.6 version.
