### ISSUE TITLE
Marlon issue?

### ISSUE THREAD

**Issue by rachel-pt** [Annosz/UIInfoSuite2#171]
Hi. I've been playing Stardew with a few mods, including the Expanded but today since updating a couple mods, I keep getting a crash in smapi, something about Marlon not being found?
It's just after I've finished the quest with Clint to blow up the big boulder at the train station and meeting Krobus which is a cutscene with Marlon.
This is what Smapi says in red:
[UI Info Suite 2] This mod failed in the Display.RenderingHud event. Technical details:
System.Collections.Generic.KeyNotFoundException: The given key 'Marlon' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Netcode.NetDictionary`5.get_Item(TKey key) in stardewvalley\Farmer\Netcode\NetDictionary.cs:line 71
   at UIInfoSuite.UIElements.ShowBirthdayIcon.DrawBithdayIcon()
   at UIInfoSuite.UIElements.ShowBirthdayIcon.OnRenderingHud(Object sender, EventArgs e)
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(Action`2 invoke, Func`2 match) in SMAPI\Framework\Events\ManagedEvent.cs:line 139

**Comment by NAF-EY** [comment]
I guess SVE cause the problem

**Comment by dobasy** [comment]
If you haven't looked into it, I think this line is the cause of the issue.

https://github.com/Annosz/UIInfoSuite2/blob/24845321fd525332c27815b6321e2da9b843e60a/UIInfoSuite2/UIElements/ShowBirthdayIcon.cs#L112

In case of Marlon from SVE, `character.isBirthday(Game1.currentSeason, Game1.dayOfMonth)` returns `True` and the others return `False`.

**Comment by tashaschmidt** [comment]
> If you haven't looked into it, I think this line is the cause of the issue.
> 
> https://github.com/Annosz/UIInfoSuite2/blob/24845321fd525332c27815b6321e2da9b843e60a/UIInfoSuite2/UIElements/ShowBirthdayIcon.cs#L112
> 
> In case of Marlon from SVE, `character.isBirthday(Game1.currentSeason, Game1.dayOfMonth)` returns `True` and the others return `False`.

I had the same problem on winter 19 which is Marlon's birthday. I tried to upload a smapi log but it said it was too big haha! So I tried to reproduce it on a fresh day so maybe it would be smaller and now I'm not getting it. Checked the calendar and yep, yesterday was Marlon's birthday.

**Comment by KAVH5** [comment]
Hi, I think I am having the same issue, an am not really understanding if there is a solution, yet, to fix the problem. I thought I'd drop my log and the specific error to give you more if you need it.

I do have a lot of mods but I'm not sure I have even met a Bill yet lol.

LOG: 
https://smapi.io/log/1c8fabc87f1d41a9bef9a74f011af3c7

ERROR: 
14:31:30 | ERROR | UI Info Suite 2 | This mod failed in the Display.RenderingHud event. Technical details:  System.Collections.Generic.KeyNotFoundException: The given key 'Bill' was not present in the dictionary. at System.Collections.Generic.Dictionary`2.get_Item(TKey key) at Netcode.NetDictionary`5.get_Item(TKey key) in stardewvalley\Farmer\Netcode\NetDictionary.cs:line 71 at UIInfoSuite.UIElements.ShowBirthdayIcon.DrawBithdayIcon() at UIInfoSuite.UIElements.ShowBirthdayIcon.OnRenderingHud(Object sender, EventArgs e) at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(Action`2 invoke, Func`2 match) in SMAPI\Framework\Events\ManagedEvent.cs:line 139
-- | -- | -- | --| repeats 34192 times

I appreciate the updates for this mod an am sorry to bother you.

**Comment by KAVH5** [comment]
In addition, the game was still "playable" if that is what we will call it! The lag was awful though, so I went to the next day.

NEW DAY LOG WITH ERROR STILL IN LOG:
https://smapi.io/log/899b504775664c98961f094187553f88

And than one more if you were to need it, a log showing the next day loaded without the error. I closed and reloaded my game so that the 'Bill' characters birthday was no longer my load up day.

NEW DAY LOG AFTER BILLS BIRTHDAY:
https://smapi.io/log/b318cb8e767e47d0b885bfe64f10c937

You may not need any of that but just wanted to make sure all the bases were covered.

**Comment by brucethemoose** [comment]
Getting this as well: https://smapi.io/log/15c27f8b5c694dc98f612da9690e0a84?Page=20&PerPage=1000&Sections=ModsList%7EContentPackList

**Comment by brucethemoose** [comment]
> Hi, I think I am having the same issue, an am not really understanding if there is a solution, yet, to fix the problem. I thought I'd drop my log and the specific error to give you more if you need it.
> 
> I do have a lot of mods but I'm not sure I have even met a Bill yet... or maybe I have so many now I can't even remember everybody, lol.
> 
> LOG: https://smapi.io/log/1c8fabc87f1d41a9bef9a74f011af3c7
> 
> ERROR: 14:31:30 | ERROR | UI Info Suite 2 | This mod failed in the Display.RenderingHud event. Technical details: System.Collections.Generic.KeyNotFoundException: The given key 'Bill' was not present in the dictionary. at System.Collections.Generic.Dictionary`2.get_Item(TKey key) at Netcode.NetDictionary`5.get_Item(TKey key) in stardewvalley\Farmer\Netcode\NetDictionary.cs:line 71 at UIInfoSuite.UIElements.ShowBirthdayIcon.DrawBithdayIcon() at UIInfoSuite.UIElements.ShowBirthdayIcon.OnRenderingHud(Object sender, EventArgs e) at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(Action`2 invoke, Func`2 match) in SMAPI\Framework\Events\ManagedEvent.cs:line 139 -- | -- | -- | --| repeats 34192 times
> 
> I appreciate the updates for this mod an am sorry to bother you.

Disable the show birthdays option in the ui info suite config menu.

**Comment by KAVH5** [comment]
> > Hi, I think I am having the same issue, an am not really understanding if there is a solution, yet, to fix the problem. I thought I'd drop my log and the specific error to give you more if you need it.
> > I do have a lot of mods but I'm not sure I have even met a Bill yet... or maybe I have so many now I can't even remember everybody, lol.
> > LOG: https://smapi.io/log/1c8fabc87f1d41a9bef9a74f011af3c7
> > ERROR: 14:31:30 | ERROR | UI Info Suite 2 | This mod failed in the Display.RenderingHud event. Technical details: System.Collections.Generic.KeyNotFoundException: The given key 'Bill' was not present in the dictionary. at System.Collections.Generic.Dictionary`2.get_Item(TKey key) at Netcode.NetDictionary`5.get_Item(TKey key) in stardewvalley\Farmer\Netcode\NetDictionary.cs:line 71 at UIInfoSuite.UIElements.ShowBirthdayIcon.DrawBithdayIcon() at UIInfoSuite.UIElements.ShowBirthdayIcon.OnRenderingHud(Object sender, EventArgs e) at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(Action`2 invoke, Func`2 match) in SMAPI\Framework\Events\ManagedEvent.cs:line 139 -- | -- | -- | --| repeats 34192 times
> > I appreciate the updates for this mod an am sorry to bother you.
> 
> Disable the show birthdays option in the ui info suite config menu.

I thought I was starting to get comfortable going in and editing things but obviously not. It is completely going over my head what you mean

My config file only has :
{
  "ShowOptionsTabInMenu": true,
  "ApplyDefaultSettingsFromThisSave": "JohnDoe_123456789",
  "OpenCalendarKeybind": "C",
  "OpenQuestBoardKeybind": "F"
}

and my config menu only gives four options, being :
Show options in in-game menu
Apply default setting from this save
Open calendar keybind 
Open quest board keybind

**Comment by KAVH5** [comment]
I did this for now! Hopefully these were the correct steps.
Went into the Stardew folder, opened the mods folder, clicked into UIInfoSuite2 folder, than my data folder.
Once in the data folder I clicked onto my save
A notepad opened up an around the 14th line there is a default setting of "ShowBirthdayIcon": true,
I am assuming this is where I make the change to false, so I did

**Comment by brucethemoose** [comment]
> > > Hi, I think I am having the same issue, an am not really understanding if there is a solution, yet, to fix the problem. I thought I'd drop my log and the specific error to give you more if you need it.
> > > I do have a lot of mods but I'm not sure I have even met a Bill yet... or maybe I have so many now I can't even remember everybody, lol.
> > > LOG: https://smapi.io/log/1c8fabc87f1d41a9bef9a74f011af3c7
> > > ERROR: 14:31:30 | ERROR | UI Info Suite 2 | This mod failed in the Display.RenderingHud event. Technical details: System.Collections.Generic.KeyNotFoundException: The given key 'Bill' was not present in the dictionary. at System.Collections.Generic.Dictionary`2.get_Item(TKey key) at Netcode.NetDictionary`5.get_Item(TKey key) in stardewvalley\Farmer\Netcode\NetDictionary.cs:line 71 at UIInfoSuite.UIElements.ShowBirthdayIcon.DrawBithdayIcon() at UIInfoSuite.UIElements.ShowBirthdayIcon.OnRenderingHud(Object sender, EventArgs e) at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(Action`2 invoke, Func`2 match) in SMAPI\Framework\Events\ManagedEvent.cs:line 139 -- | -- | -- | --| repeats 34192 times
> > > I appreciate the updates for this mod an am sorry to bother you.
> > 
> > 
> > Disable the show birthdays option in the ui info suite config menu.
> 
> I thought I was starting to get comfortable going in and editing things but obviously not. It is completely going over my head what you mean
> 
> My config file only has : { "ShowOptionsTabInMenu": true, "ApplyDefaultSettingsFromThisSave": "JohnDoe_123456789", "OpenCalendarKeybind": "C", "OpenQuestBoardKeybind": "F" }
> 
> and my config menu only gives four options, being : Show options in in-game menu Apply default setting from this save Open calendar keybind Open quest board keybind
> 
> I also have the 'Show Birthday' mod an am not sure if this is causing any issue https://www.nexusmods.com/stardewvalley/mods/7495?tab=posts

Oh you dont need to do any of that, use this mod: 

https://www.nexusmods.com/stardewvalley/mods/5098?tab=files

**Comment by KAVH5** [comment]
Of course, I 

> > > > Hi, I think I am having the same issue, an am not really understanding if there is a solution, yet, to fix the problem. I thought I'd drop my log and the specific error to give you more if you need it.
> > > > I do have a lot of mods but I'm not sure I have even met a Bill yet... or maybe I have so many now I can't even remember everybody, lol.
> > > > LOG: https://smapi.io/log/1c8fabc87f1d41a9bef9a74f011af3c7
> > > > ERROR: 14:31:30 | ERROR | UI Info Suite 2 | This mod failed in the Display.RenderingHud event. Technical details: System.Collections.Generic.KeyNotFoundException: The given key 'Bill' was not present in the dictionary. at System.Collections.Generic.Dictionary`2.get_Item(TKey key) at Netcode.NetDictionary`5.get_Item(TKey key) in stardewvalley\Farmer\Netcode\NetDictionary.cs:line 71 at UIInfoSuite.UIElements.ShowBirthdayIcon.DrawBithdayIcon() at UIInfoSuite.UIElements.ShowBirthdayIcon.OnRenderingHud(Object sender, EventArgs e) at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(Action`2 invoke, Func`2 match) in SMAPI\Framework\Events\ManagedEvent.cs:line 139 -- | -- | -- | --| repeats 34192 times
> > > > I appreciate the updates for this mod an am sorry to bother you.
> > > 
> > > 
> > > Disable the show birthdays option in the ui info suite config menu.
> > 
> > 
> > I thought I was starting to get comfortable going in and editing things but obviously not. It is completely going over my head what you mean
> > My config file only has : { "ShowOptionsTabInMenu": true, "ApplyDefaultSettingsFromThisSave": "JohnDoe_123456789", "OpenCalendarKeybind": "C", "OpenQuestBoardKeybind": "F" }
> > and my config menu only gives four options, being : Show options in in-game menu Apply default setting from this save Open calendar keybind Open quest board keybind
> > I also have the 'Show Birthday' mod an am not sure if this is causing any issue https://www.nexusmods.com/stardewvalley/mods/7495?tab=posts
> 
> Oh you dont need to do any of that, use this mod:
> 
> https://www.nexusmods.com/stardewvalley/mods/5098?tab=files
> 
> It's definitely a staple of any modded game.

Of course, thank you! I have that mod and that is where I said for some reason I only have the four options of 

Show options in in-game menu
Apply default setting from this save
Open calendar keybind
Open quest board keybind

 I have no idea why but I think I "fixed" it for now doing what I did so we're good lol!!

**Comment by Annosz** [comment]
Hello guys! Sorry this issue took so much time to fix, I just did not realized that it is actually a breaking error which makes you unable to play the game...
I uploaded version 2.2.4 of the mod, which is the fix for this issue - you will be able to use the birthday icon again.

**Comment by brucethemoose** [comment]
> Hello guys! Sorry this issue took so much time to fix, I just did not realized that it is actually a breaking error which makes you unable to play the game... I uploaded version 2.2.4 of the mod, which is the fix for this issue - you will be able to use the birthday icon again.

Thanks!... but it seems this release is source only, and doesn't have a compiled zip?

**Comment by Annosz** [comment]
Yeah, there was a small problem, my antivirus blocked the upload of the file and I did not notice in time... It is fixed now :)
