### ISSUE TITLE
Mia Error

### ISSUE THREAD

**Issue by ADemonicChild** [Annosz/UIInfoSuite2#172]
https://smapi.io/log/0ecb8bf0d23e4ba29efb7a97cf284b25 -> heres the link to my smapi log; error is at the bottom.
Pretty sure the error has to do with the "Always Raining in the Valley" mod. Everytime I boot up a previously owned world, or a new world, this error at the bottom appears, and keeps appearing unless I enter select mode in smapi. It will keep writing the same error over and over again in my smapi log, until I enter select mode. This ends up crashing my game every time I let it continue flowing through Smapi, so idk. Pls help if you can.

**Comment by Annosz** [comment]
Duplicate of #167 but still leaving this issue open as it has a useful SMAPI log.

**Comment by Annosz** [comment]
Hi! Sorry this issue took so much time to fix, I just did not realized that it is actually a breaking error which makes you unable to play the game...
I uploaded version 2.2.4 of the mod, which is the fix for this issue - you will be able to use the birthday icon again.

**Comment by AylinvanRossum** [comment]
The issue still persists. Sorry for the very long SMAPI logs, I got tons of mods xD I didn't realise it was spamming my logs, until I went to bed and it took a long time to continue. 

What I did previously to avoid the logs from being spammed (to the point of the game crashing), was to disable the icon for the birthday. So there is a way to bypass it, but still, not how it should and I can imagine not everyone thinking about that.

SMAPI logs below, hopefully I did it correctly.

https://smapi.io/log/26cf8fe1258b47d9a47fb3c189ee5c17

**Comment by Annosz** [comment]
Hi @Aylin-NL! I will reopen the issue and check it again for Mia.
However, in your logs I do not see any error message. Is it possible that you created the logs with the birthday icon turned off? I would say that you should upload a log when the game crashes and has the red text, but I guess you are already pass Mia's birthday, so you can't test it for another year :) I will try to reproduce the issue.

**Comment by ADemonicChild** [comment]
Actually, it’s there in the smapi log. I just saw went through it. You have to go to the second page of the smapi log, which I didn’t notice until I looked around. But the error is happening for a different npc. I have not gotten any errors with the Raining in the Valley mod.

**Comment by Annosz** [comment]
And it turns out I was the one who did not know you can turn pages in the SMAPI log :) Thanks, I will take a look at it.

**Comment by Annosz** [comment]
I was still not able to reproduce this issue on my environment, but I made some changes which hopefully can fix problems with the custom NPC birthdays. I've created a pre-release for [version 2.2.5](https://github.com/Annosz/UIInfoSuite2/releases/tag/2.2.5) of the mod where I hope it will work already. Feel free to check it out and report back if there is still a problem.

**Comment by Annosz** [comment]
I hope that the issue has been fixed when the 2.2.5 version was released - as there are no report since then, I will close this issue too :)
