### ISSUE TITLE
Can't drag items via Community Center shortcut

### ISSUE THREAD

**Issue by Thjodann** [Annosz/UIInfoSuite2#175]
As the title states, everything about the Community Center shortcut works great, except for dragging items. I still have to travel to the building and do it the old-fashioned way.

**Comment by Fr3EkOut** [comment]
That's vanilla, it's not part of this mod. It's only for you to check the status of what you've donated so far, and whether you have it on you. I can't imagine the farmer has a throwing arm _that_ powerful...
