### ISSUE TITLE
Loading issue

### ISSUE THREAD

**Issue by LacyHart** [Annosz/UIInfoSuite2#183]
I have installed the mod a few times and in sampi, I keep seeing this message: - UI Info Suite 2 2.2.4 because its DLL 'UIInfoSuite2.dll' doesn't exist.

Is there something wrong that I did? Because it is not loading correctly

**Comment by drewhoener** [comment]
I believe there was an issue with @Annosz file upload with a couple versions.
Have you tried downloading the latest? It seems to contain the .dll now https://github.com/Annosz/UIInfoSuite2/releases/tag/2.2.4

**Comment by Annosz** [comment]
It is also possible that you downloaded the source code for the mod, not the mod files itself.
If you go to the main page, there is an "[If you are here to install the mod](https://github.com/Annosz/UIInfoSuite2)" section, read that and make sure you followed the instructions. But as @drewhoener wrote, youcan just go the the [https://github.com/Annosz/UIInfoSuite2/releases/tag/2.2.4](https://github.com/Annosz/UIInfoSuite2/releases/tag/2.2.4) page and download the .zip file.
