### ISSUE TITLE
Needs .dll file

### ISSUE THREAD

**Issue by LG874** [Annosz/UIInfoSuite2#194]
SMAPI skips the mod due to missing .dll file. Did I do something wrong or does everyone have this problem?

**Comment by SolarisShadow** [comment]
Did you go to the [Releases page](https://github.com/Annosz/UIInfoSuite2/releases) on the side, or download the source code from the main page (the green Code > Download button on the main page)? As the source code will not work where as the releases will.

**Comment by LG874** [comment]
I downloaded the latest release from the releases page. I did this several times because I thought my computer possibly downloaded the files wrong.

**Comment by LG874** [comment]
I found out what was happening. My computer was messing with the download and even though I clicked the zip file it was somehow downloading the wrong files every time. I finally got it fixed though.

**Comment by Annosz** [comment]
Hi! I'm glad it's fixed :) I will include this on my checklist if someone else asks about the missing dll, it's quite a common problem so maybe it will help others.
