### ISSUE TITLE
Tooltips render in incorrect layer

### ISSUE THREAD

**Issue by ghost** [Annosz/UIInfoSuite2#203]
This is a small issue but the tooltips for UI Info Suite often render in the incorrect layer.

Issue #1: Tooltips for world objects continue to render behind most of the game's menus. This can be seen by opening the menu while hovering over any craftable. A simple check for `Game1.activeClickableMenu is not null` should probably fix this.

Issue #2: The UI Info Suite's own config tab renders above the game's tooltips.
[Screenshot](https://i.imgur.com/iEcMZJR.png)
I have not checked the implementation but this can often be fixed by changing a postfix into a transpiler that calls a subroutine.

**Comment by Annosz** [comment]
Hi @ghost! @tqdv created a solution for the first part, which I will include in the v2.2.7 release.
For the second part I will create a new issue, so it can be tracked separately: #250

**Comment by Annosz** [comment]
Turns out the second part was already handled in #214, so the whole story is fixed now.
