### ISSUE TITLE
[Feature] Dungeon level display

### ISSUE THREAD

**Issue by NightFright2k19** [Annosz/UIInfoSuite2#205]
An option to show on which level you are in the dungeons (e.g. Mines, Skull Caverns) would be nice and really helpful, especially in the Skull Caverns when trying to reach level 100 for the Qi quest.

**Comment by Annosz** [comment]
I don't quite understand this, as both in the Mines and the Skull Cavern you have a level indicator in the upper left corner, it's part of the base game. Which platform are you playing on?

**Comment by NightFright2k19** [comment]
Oh dang it... I didn't see this since I am using the "NPC Map Locations" mod with the minimap, which is placed in the top left corner. So I didn't know there was a counter at all. Sorry, my bad. This can be closed, then.
