### ISSUE TITLE
Incorrect operation

### ISSUE THREAD

**Issue by mazlguy** [Annosz/UIInfoSuite2#208]
Some animals arent marked for "Need Petting" and "Has item yield" icons in the mornings. No error shows in smapi.

**Comment by mazlguy** [comment]
No error shows in smapi.

**Comment by tqdv** [comment]
Hi! For the animals that don't have item yield icons, do they actually have an item yield?

**Comment by mazlguy** [comment]
Yes, they do.

**Comment by tqdv** [comment]
Hmmm that's weird indeed.

Could you take a screenshot showing the problem and also upload your smapi logs at https://smapi.io/log ? I'll try to reproduce your issue.

**Comment by mazlguy** [comment]
Sure thing, here you go.
![StardewValley](https://user-images.githubusercontent.com/108584507/179087475-d5496b77-55ab-419b-b1e8-7a20f82dc4cb.png)

Smapi log. https://smapi.io/log/c34f2f21f66e4fe18e85e73557c47bff

**Comment by mazlguy** [comment]
This second image is whit the Auto Graver machine.
![Stardew Valley2](https://user-images.githubusercontent.com/108584507/179089934-34648c85-bf87-4048-a2cb-86a34b8586da.png)

**Comment by tqdv** [comment]
Hmmm, do you happen to have full hearts with those two circled animals? If so, is the `Show when animal need pets` > `Hide on max friendship` option activated ?

Also, I don't understand what you mean by the "has item yield" icon missing. Aren't the items already collected by the auto-grabber, so that if you try to milk the cow, it won't work?

**Comment by mazlguy** [comment]
Yeah, I have full hearts whit all animals and seems the item yield icon functions correctly but the pet one not.

**Comment by tqdv** [comment]
Okay, could you try checking in the UI Info Suite options tab, if the option `Show when animal need pets` > `Hide on max friendship option activated` is checked ? If so, you can uncheck it to show the pets indicator even if they're at max friendship.

**Comment by mazlguy** [comment]
DAMN, that worked, I didn't know that option existed and now I'm feeling like an fool, thanks and sorry for bothering you.
