### ISSUE TITLE
Map Locations Inaccurate on Fall 15 for the Desert

### ISSUE THREAD

**Issue by Zamiell** [Annosz/UIInfoSuite2#22]
Sandy's birthday is on Fall 15. On this day, Emily will go to Desert in order to visit Sandy. 

During this day, Emily will first go to the shop (I think). At some point, they will end up outside standing somewhat near to the Desert Trader. I haven't actually mapped out their specific NPC movements for the day.

Regardless, during this day the positions for Emily and Sandy on the map will be undefined at points, so the mod needs to know about the Desert.

**Comment by Annosz** [comment]
I wasn't really able to find any moment on that day when they were off the map - both of them were drawn in the desert when i followed them through the day.

![desert](https://user-images.githubusercontent.com/10620868/104046207-01397900-51e0-11eb-9fb5-3c2e5f1a6ad1.png)

However, I will fix that issue that always bothered me: Sandy's shop should be drawn _under_ the road, and I will place them closer to the heart of the desert on this day.

**Comment by Zamiell** [comment]
Oh, interesting. Thanks Annosz!
