### ISSUE TITLE
Can we get the ability not show XP popups but still show the XP bar in corner?

### ISSUE THREAD

**Issue by argon932** [Annosz/UIInfoSuite2#235]
If I disable show experience gains, it also disables the experience bar in the corner. I run mods that make things like tappers grant XP, so I am constantly seeing XP popups around my character while roaming around, it's a bit distracting, but I cannot find a way to disable that without completely disabling the XP bar in the corner (which I want to keep).

Given these are 3 separate options, I assume they are suppose to work separately but disabling "Show experience gain" seems to disable the other 2 as well.

Thanks!

**Comment by argon932** [comment]
It seems I just needed to restart my game after disabling XP gain. Now the bar is showing correctly with it disabled! Closed.

**Comment by lightsourced** [comment]
+1!!
