### ISSUE TITLE
UIinfosuite2.dll does not exist

### ISSUE THREAD

**Issue by yasarra** [Annosz/UIInfoSuite2#244]
Hi,

Sorry to bother you.  I'm sure you're busy with real life stuff, but...
Your current version of UIInfoSuite2 is producing an error in Stardew Valley.
This is the error I get when trying to load the game:

[SMAPI] These mods could not be added to your game.
UI Info Suite 2 2.2.6 because its DLL 'UIInfoSuite2.d.ll' doesn't exist.

After redownloading, I can confirm that the file is missing.

**Comment by tqdv** [comment]
Hi! You probably downloaded the source code. Could you try again with [this link](https://github.com/Annosz/UIInfoSuite2/releases/download/2.2.6/UIInfoSuite2.zip)?

**Comment by yasarra** [comment]
Oh, perfect.  Thank you so much. :)
