### ISSUE TITLE
My save file won't work with UI Info Suite 2 anymore

### ISSUE THREAD

**Issue by dewwdrp** [Annosz/UIInfoSuite2#248]
So for some reason today, UIInfoSuite2 stopped working on my main save today. It was working perfectly fine last night, the only change I've made was updating my version of SMAPI, and I downloaded the regular version. Also to check I loaded into a different save and the mod still loads and works perfectly on the other saves I have, just not my main save.... so I guess my save doesn't like this mod anymore even though it was working fine literally last night?

Now my question is, is there any way I could possibly make this mod work on my main save file again? D:

This is my log when I load the save in question, not sure if it helps at all but thought I'd provide it just in case it does. https://smapi.io/log/049a88b3d7504f8d962901b96170249a

**Comment by tqdv** [comment]
Thanks for the log! Though that is *indeed* a weird error that I can't reproduce on my computer.

Could you install this build of UI Info Suite 2 with debug information: [UIInfoSuite2 v2.2.6 debug.zip](https://github.com/Annosz/UIInfoSuite2/files/9763878/UIInfoSuite2.v2.2.6.debug.zip); and upload the log here, to see if the error message has line numbers?

<details><summary>Copy of the log error (for posterity)</summary>

```
	This mod failed in the GameLoop.SaveLoaded event. Technical details: 
NullReferenceException: Object reference not set to an instance of an object.
   at UIInfoSuite2.UIElements.ShowItemHoverInformation..ctor(IModHelper helper)
   at UIInfoSuite2.Options.ModOptionsPageHandler..ctor(IModHelper helper, ModOptions options, Boolean showPersonalConfigButton)
   at UIInfoSuite2.ModEntry.OnSaveLoaded(Object sender, SaveLoadedEventArgs e)
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101
```

</details>

**Comment by dewwdrp** [comment]
Done! Hopefully this helps some, at least if my save can't be fixed hopefully it can be prevented from happening to other's save files lol. Also, I wanted to say thank you for taking the time to keep this mod updated AND share it with everyone, I know nothing about modding, but I know it has to be a lot of work and effort, and I wanted to let you know I appreciate it.

**Comment by tqdv** [comment]
Hmmm, it seems that the mod can't find Gunther in the world. In that save file, where is Gunther? Is he still in the library or is he somewhere else like a modded location?

**Comment by dewwdrp** [comment]
He's in the library, I mean, he does move around because I have SVE installed and after you donate 60 items he turns into a giftable NPC, but he still usually hangs out at the library/museum.

**Comment by tqdv** [comment]
If you're still interested, I made a new build that will hopefully fix the issue (in UI Info Suite 2 at least):  [UIInfoSuite2 v2.2.6 fix missing Gunther.zip](https://github.com/Annosz/UIInfoSuite2/files/9769242/UIInfoSuite2.v2.2.6.fix.missing.Gunther.zip)

**Comment by dewwdrp** [comment]
I haven't made a complete decision yet on that file but that did fix it for me! Thank you so much!

**Comment by Annosz** [comment]
Thank you @tqdv for the quick fix again!
