### ISSUE TITLE
Inaccurate Locations of People, while playing a Coop game as guest

### ISSUE THREAD

**Issue by DonPavlov** [Annosz/UIInfoSuite2#25]
While playing the game in coop mode as guest the map still shows every person on the map. But just at there default home location, not the location, where they should be.

**Comment by friederschueler** [comment]
Not only this, but there are many other coop issues. I copied this from the issue from the original repository.
I like the upgrades this fork has and I am willing to contribute, but I am not sure where to start implementing the new PerScreen<T>? Are you willing to support this?

> When another farmer joins in local co-op (split screen), the experience tracker will endlessly repeat experience gain notifications as soon as they join, even though no one is gaining experience. Each character after the first introduces more, so with three players each screen will see repeating experience notifications at two different points on screen, that seem to track the movements (but not actual location) of the other farmers. This seems to lag the game, especially as more local players join.
> 
> You can't open the mod's config menu in split screen (clicking the icon does nothing). The icon sometimes moves, but I'm not sure under what circumstances.
> 
> Icons for luck (and probably others) are displayed for each character for every character. So if there are three local players, three luck icons are displayed on each character's (split) screen.
> 
> The experience bar for all characters seems to only show the experience progress level of the last player to join (so all three screens see the experience bar of player three).
> 
> (Tested using the UI Info Suite unofficial update on SMAPI 3.8.2 develop, as 3.8.1 has other local co-op bugs)
> 
> I'm guessing a lot of this can be fixed by using the new PerScreen<T>.

**Comment by Annosz** [comment]
@friederschueler  Of course, I'm happy if anyone contributes to the project. I haven't looked into the coop related issues myself, as I'm starting to think it will be difficult to solve (just like the [zoom issues](https://github.com/Annosz/UIInfoSuite2/issues/16)), but feel free to try :)

I also removed myself from PRs I haven't started so you can choose anything from there too. I think the [Robin Building Status](https://github.com/Annosz/UIInfoSuite2/issues/20) is the easiest and best way to understand how this mod handles adding new UI icons.

**Comment by DiscipleOfEris** [comment]
I posted that issue on the original repo. I also have fixed it and submitted a PR. https://github.com/cdaragorn/Ui-Info-Suite/pull/61

I think I've gotten all the split screen and ui scale bugs. I'm thinking of moving on to make the menu compatible with the vanilla "Use Controller-Style Menus" option, but I haven't decided yet..

**Comment by DiscipleOfEris** [comment]
@DonPavlov I believe I've fixed this bug now, if you want to check https://github.com/cdaragorn/Ui-Info-Suite/pull/61.
