### ISSUE TITLE
Mod skipped

### ISSUE THREAD

**Issue by ZEkA10000** [Annosz/UIInfoSuite2#256]
I downloaded mod from [releases ](https://github.com/Annosz/UIInfoSuite2/releases)(uploaded Aug 13, because no more links to download a compiled mod) 

```
[SMAPI]    Skipped mods
[SMAPI]    --------------------------------------------------
[SMAPI]       These mods could not be added to your game.

[SMAPI]       - UI Info Suite 2 2.2.6 because it's no longer compatible. Please check for a new version at https://smapi.io/mods
```
```
 SMAPI 3.13.4 with Stardew Valley 1.5.6 (build 22018)
 ```

**Comment by tqdv** [comment]
That's weird. Could you update [SMAPI](https://smapi.io/) to the latest version (3.17.2) to see if the error still happens?

**Comment by ZEkA10000** [comment]
> That's weird. Could you update [SMAPI](https://smapi.io/) to the latest version (3.17.2) to see if the error still happens?

That's helped.

**Comment by tqdv** [comment]
Your issue seems to be fixed, so I'm marking this ticket as done.
