### ISSUE TITLE
incorrect version number on latest update

### ISSUE THREAD

**Issue by silverdragon13** [Annosz/UIInfoSuite2#265]
The version  on the site says 2.2.7 but the manifest still says 2.2.6.  Thanks

**Comment by tqdv** [comment]
Could you try again with this link https://github.com/Annosz/UIInfoSuite2/releases/download/2.2.7/UIInfoSuite2.zip ?

**Comment by silverdragon13** [comment]
I downloaded the file and verified that it is now showing the corrected version.  Thank you
