### ISSUE TITLE
[Bug] Pre-release 2.2.7 build always shows luck icon when loading save

### ISSUE THREAD

**Issue by richardsavio** [Annosz/UIInfoSuite2#267]
**This is bug report for the pre-release 2.2.7 build.**

Steps to reproduce:
1. Create a fresh save.
1. Disable the "Show luck icon" checkbox from UI Info suite's in-game Settings UI. _The luck icon is disabled immediately after you toggle the config. This is not the issue._
2. Go to bed
3. Exit to desktop
4. Reload the save
5. Luck icon shows up again

Checking the config file in the mod folder shows that the config is saved correctly. The in-game settings UI also correctly reflects this. However, the luck icon does not honour the setting when reloading the save.

This was working properly for me in 2.2.6. I haven't added any other mods when I updated UI Info Suite. This is also reproducible on a fresh save without any settings carried over (config.json or the save specific settings).

**Comment by Crufus** [comment]
I've been through the same error. I modified the json file in data folder, but the luck icon, birthday icon, and merchant icon were not fixed for my case.

**Comment by tqdv** [comment]
Hi @richardsavio and @Crufus. Could you install this version and check if it works properly now ? 
[UIInfoSuite2-v2.2.7-fix-sub-options.zip](https://github.com/Annosz/UIInfoSuite2/files/10200006/UIInfoSuite2-v2.2.7-fix-sub-options.zip)

**Comment by Crufus** [comment]
Working perfectly! Thank you :)
