### ISSUE TITLE
Invisible Robin icon while upgrading barn

### ISSUE THREAD

**Issue by HeroWillHD** [Annosz/UIInfoSuite2#270]
I'm having the same problem as #122 , I'm in fall (same as when #122 was posted, the problem also was with upgrading a barn, don't know if it has something to do with the bug) and upgraded my barn to a big barn, now I'm currently upgrading it to a deluxe barn, in the two occasions, the Robin's icon for building was invisible to me.

![Screenshot_20221214_064447](https://user-images.githubusercontent.com/88997499/207724821-6c89fc06-45ff-4230-b11c-d8c82d6462ea.png)

**Comment by tqdv** [comment]
Hi, could you upload your SMAPI log at https://smapi.io/log and link it here ?

**Comment by HeroWillHD** [comment]
> Hi, could you upload your SMAPI log at https://smapi.io/log and link it here ?

Hi! Here's the log, unfortunely my barn upgrade is already done, so there's no icon showing as of the time this log was generated, i hope that's not a problem. If it is, i could try to replicate the bug again and submit another log.
https://smapi.io/log/3af4a3cde0d54548bcc158a862ef6018

**Comment by Annosz** [comment]
Hi! I've tried to look over the mods based on your SMAPI logs. I was hoping that there is some conflict, and Anthro Characters Continued 1.5 seemed like a very good guess, as it replaces tilesheets... But I could not reproduce the issue.

@tqdv one fix I think would work is using the following values for the Robin icon:
```
_robinIconSheet = Game1.content.Load<Texture2D>("LooseSprites\\robinAtWork");
_buildingIconSpriteLocation = new Rectangle(64, 0, 64, 64);
```
But this uses a tile sheet that can be forgotten by mod authors, eg. Anthro Characters Continued 1.5 also did not replace this, so the original Robin sprites are displayed. But I guess that's better than no icons at all. Were you able to reproduce the issue? can you try if this fix works: #274 ?

**Comment by tqdv** [comment]
@Annosz, I figured out how to reproduce the issue (I think): when upgrading a building, the Robin NPC will be placed inside the building, but we don't search inside buildings in `FindRobinSpritesheet`.

**Comment by Annosz** [comment]
@tqdv in this case we should go with your solution, because of the problem I mentioned ("LooseSprites\\robinAtWork" is not updated in some Content Patcher mods).
