### ISSUE TITLE
Installation error with the newest version.

### ISSUE THREAD

**Issue by phantasiaa** [Annosz/UIInfoSuite2#273]
![image](https://user-images.githubusercontent.com/120753896/208189152-b13c183c-11e6-4d86-a605-1b4bec0f00ea.png)

I'm not sure why this issue is happening. Any help would be appreciated!

**Comment by tqdv** [comment]
Hi, try this link: https://github.com/Annosz/UIInfoSuite2/releases/download/2.2.9/UIInfoSuite2.zip

**Comment by phantasiaa** [comment]
> 

thanks, i'll try in a little and let you know if it works

**Comment by tqdv** [comment]
Closing this as I assume you managed to make it work.
