### ISSUE TITLE
Error causes disconnect when starting new day in co-op.

### ISSUE THREAD

**Issue by LJNeon** [Annosz/UIInfoSuite2#279]
![image](https://user-images.githubusercontent.com/23249107/209780228-88edb47d-69cc-4943-be49-9be93372610c.png)

**Comment by tqdv** [comment]
Hi, does this version ([UIInfoSuite2-v2.2.9-log-robin-farm.zip](https://github.com/Annosz/UIInfoSuite2/files/10314520/UIInfoSuite2-v2.2.9-log-robin-farm.zip)) at least turn that error into a warning ?
Tbh I’m surprised this error causes a disconnect. Is it local co-op or online ? Is it the host getting disconnected or the farmhands ?

**Comment by LJNeon** [comment]
I am a farmhand and I was disconnected by this error. As for the version you linked, I have yet to get this error again and I didn't want to delay this reply any further.

**Comment by Annosz** [comment]
I think if there is no other occurrence of this error, we can close this. It was most likely related to the Robin bug #270, and it should be solved by the update @tqdv linked.
