### ISSUE TITLE
Erro de instalação da nova versão.

### ISSUE THREAD

**Issue by brancadeneve78** [Annosz/UIInfoSuite2#281]
Não estou conseguindo baixar a nova versão, está dando erro quando abro o jogo. O que poderia ser?
![IMG_20221230_160101](https://user-images.githubusercontent.com/121691122/210104001-da47b8d5-6272-49e9-b280-a33565ffc66d.jpg)

**Comment by tqdv** [comment]
Try with this link : https://github.com/Annosz/UIInfoSuite2/releases/download/2.2.9/UIInfoSuite2.zip

**Comment by brancadeneve78** [comment]
Ta bem, já entro em contato para dizer se foi, inclusive é para baixar só esse que está no link ou os outros dois itens lá do início também além do "UiInfoSuite2.zip"?

**Comment by tqdv** [comment]
I’m not sure I understand but :
- Remove the UIInfoSuite2-2.2.9 folder from your mod folder
- Download https://github.com/Annosz/UIInfoSuite2/releases/download/2.2.9/UIInfoSuite2.zip
- Extract it in your mod folder

**Comment by brancadeneve78** [comment]
Fiz isso que disse e está dando esse erro aqui:

![Screenshot_2022-12-30-17-20-31-527_com zane stardewvalley](https://user-images.githubusercontent.com/121691122/210109120-f0b97879-337c-460c-8032-3200a75b25ce.jpg)

**Comment by tqdv** [comment]
I just realized you're on Android !  I'm not sure UI Info Suite 2 works on mobile because we target Stardew Valley 1.5.6.

**Comment by brancadeneve78** [comment]
Ah, faz sentido, eu não sabia kkkk, ta bom, muito obrigada então
