### ISSUE TITLE
[Bug?] NPCs walking through objects

### ISSUE THREAD

**Issue by jtoya85** [Annosz/UIInfoSuite2#294]
I just downloaded this mod and while I like it there seems to be a small issue with my game. I've seen NPCs walking through objects. I walked out of the community center and saw someone, I don't know everyone's names' to faces yet, walking from the left side of the screen through the water fountain and bushes. I'm not sure if it's a mod conflict but the other mods I have installed are:
CJBCheatsMenu
Custom Reminders
Save Anywhere
To Dew
This one, UI Info Suite

**Comment by jtoya85** [comment]
Well, I haven't seen this reproduced in my own game again so I guess it's not a bug.

**Comment by tqdv** [comment]
Hi, UIInfoSuite2 doesn't modify the game's logic, so it's quite unlikely to be from us.

**Comment by jtoya85** [comment]
I don't know how the mod of configured or how it affects the game code but with all due respect I didn't have the issue before installing UIinfosuite. I did see another instance of Willy standing it in the ocean again but it was just the one additional time and not again since. I'm just trying to report what happened after a step I took with my mod selection.
