### ISSUE TITLE
Robin building icon not appearing

### ISSUE THREAD

**Issue by geenaxion** [Annosz/UIInfoSuite2#296]
All of the other icons are working fine except when Robin is building something for me.

UI Info Suite 2 | ShowRobinBuildingStatusIcon: Could not find Robin spritesheet
-- | --

https://smapi.io/log/5f5f19b3e96d46748794630d5698fbbd

**Comment by ReaperTZ** [comment]
me too,I tried to open a new archive, but the new archive can display the Robin work icon normally, but switching to the old archive smapi shows that it cannot be found

**Comment by ReaperTZ** [comment]
https://smapi.io/log/ea720df2a2d344afb4bed1dad4220e61

**Comment by tqdv** [comment]
Linking to GitHub issue #122

**Comment by Annosz** [comment]
Related issue: https://github.com/Annosz/UIInfoSuite2/issues/330
Should be solved by #333, as the other mentioned issue.
