### ISSUE TITLE
ShowRobinBuildingStatusIcon: Could not find Robin spritesheet.

### ISSUE THREAD

**Issue by ReaperTZ** [Annosz/UIInfoSuite2#299]
Robin's icon suddenly showed that it could not be found. I remember working icons can be displayed normally at first, but for some reason, smapi suddenly showed that the Robin work icon could not be found.Then the Robin work icon disappeared, but when my mouse moved to the transparent position, it could still display information, but the icon was not displayed

I tried to open a new archive,the new archive can display the Robin work icon normally, but when i switching to the old archive smapi shows that it cannot be found

I guess it's not a mod conflict problem, maybe a code problem?

https://smapi.io/log/ea720df2a2d344afb4bed1dad4220e61

**Comment by AngeryCinnabon** [comment]
Having the same issue. Here's my log
https://smapi.io/log/1272786ff5cf49f5ad960c7f4e3b986e

**Comment by tqdv** [comment]
Commenting so GitHub links it: same issue as #122.

**Comment by Annosz** [comment]
Related issue: https://github.com/Annosz/UIInfoSuite2/issues/330
Should be solved by https://github.com/Annosz/UIInfoSuite2/pull/333, as the other mentioned issue.
