### ISSUE TITLE
Missing UI Info Suite 2 on Nexus mode website

### ISSUE THREAD

**Issue by shinkek** [Annosz/UIInfoSuite2#300]
Hello. When I wanted to download a new version of the mod, I went to Nexus mode and found that it was deleted...Why is it removed?
![trouble](https://user-images.githubusercontent.com/125717789/219830767-04c63871-aa12-403c-964d-cb66e1da6770.png)

**Comment by tqdv** [comment]
Because that version of UI Info Suite 2 wasn't released by us.
Actually, no version of UI Info Suite 2 can be uploaded on Nexus unless we have cdaragorn's approval see #292 .
