### ISSUE TITLE
SMAPI skips mod when loading

### ISSUE THREAD

**Issue by oliver-sharplin** [Annosz/UIInfoSuite2#312]
When loading SMAPI, this mod is skipped.

Other mods:
- LookupAnything
- TimeSpeed
- WinterGrass
- NPCMapLocations

See image below for console log.

![image](https://user-images.githubusercontent.com/78570176/235105095-b260af42-bb3a-48a6-8288-588882716ec7.png)

**Comment by Annosz** [comment]
Hi! I think you are not actually using our mod, but the old version of UI Info Suite, which is outdated. If you want to use UIInfoSuite 2, go to the main page here on Github, and you can see a section titled [If you are here to install the mod
](https://github.com/Annosz/UIInfoSuite2#if-you-are-here-to-install-the-mod) - just follow the instructions there.

**Comment by oliver-sharplin** [comment]
Ah right makes sense. Thank you for your quick response.

Could I recommend that you link version 2 in the Nexus Mods page of version 1 ([here](https://www.nexusmods.com/stardewvalley/mods/1150)), so that people who follow a link to the mod can find themselves to the version 2 release?

Also, my favourite mod so thank you for the effort you've put into it!

**Comment by Annosz** [comment]
Sadly I'm not the author of the original mod, so I cannot modify what is being displayed there :) We would gladly put our mod on the Nexus as a separate downloadable mod, but we do not have the approval from the original author for that, so only this way remains.
