### ISSUE TITLE
UI Info Suite 2 Not Running in Smapi

### ISSUE THREAD

**Issue by mysoggywaffle** [Annosz/UIInfoSuite2#323]
Hi! I've been trying to get this downloaded and when I run smapi, it doesn't show up anywhere in the running code or in my parser log.

[SMAPI-latest.txt](https://github.com/Annosz/UIInfoSuite2/files/12139661/SMAPI-latest.txt)

![Screenshot (1)](https://github.com/Annosz/UIInfoSuite2/assets/140343351/bc49bca3-12f4-4e16-afef-f86fc2a3d81d)
![Screenshot (2)](https://github.com/Annosz/UIInfoSuite2/assets/140343351/368982e4-4eba-44fa-961b-b2aeff897b59)

Above I have my latest log and screenshots of all of my mods. You can see UI at the bottom.

Thanks!

**Comment by tqdv** [comment]
Hey @mysoggywaffle

Looking at the log, did you forget to unzip UIInfoSuite2.zip ?
> [14:12:49 TRACE SMAPI]   Ignored loose files: Better 14 Heart Event for Shane-13654-1-1-1662410723.zip, UIInfoSuite2.zip

**Comment by tqdv** [comment]
Closing this issue since I hope you figured it out. If you need help, feel free to reopen it !
