### ISSUE TITLE
ShowRobinBuildingStatusIcon: Could not find Robin spritesheet.

### ISSUE THREAD

**Issue by AngeryCinnabon** [Annosz/UIInfoSuite2#330]
![image](https://github.com/Annosz/UIInfoSuite2/assets/24904313/b6239204-0f14-491b-83f4-6849aad0f181)
Robin's image doesn't show up in the ui, but it does show the progress (although invisible as the image shows)
This only became a problem today, I was able to get a coop built without this occurring literally a day ago.
Here's my log: https://smapi.io/log/1272786ff5cf49f5ad960c7f4e3b986e

**Comment by tqdv** [comment]
Hi, this was fixed a while ago in the code (ee77b96) but never released.

**Comment by AngeryCinnabon** [comment]
Thank you! sorry I brought this up even though it was already noted, I didn't notice the other reports lol.

**Comment by tqdv** [comment]
No you did the right thing ! I should've released the fix a long time ago. I just didn't have the time to do it ^^"

**Comment by drewhoener** [comment]
Should be resolved by merge of #333
