### ISSUE TITLE
minimap on the left 

### ISSUE THREAD

**Issue by leprazs** [Annosz/UIInfoSuite2#332]
recently I was playing when suddenly a minimap on the left of the screen opened, I tried in several ways to close it I uninstalled possible mods and even so it didn't come out, I believe it is some hotkey of this mod.

**Comment by tqdv** [comment]
That's weird, because I don't think UIInfoSuite2 has a minimap.
Could you provide a screenshot and upload your log to https://smapi.io/log/ ?

**Comment by leprazs** [comment]
> That's weird, because I don't think UIInfoSuite2 has a minimap. Could you provide a screenshot and upload your log to https://smapi.io/log/ ?

I managed to fix the bug, somehow even though I removed my NPCMapLocation mod, it stayed on the interface, I did a file restore and everything was back to normal which seems very strange to me. Anyway thank you very much for your attention
