### ISSUE TITLE
Animals don't show petting symbol when at full hearts

### ISSUE THREAD

**Issue by CircusSeal** [Annosz/UIInfoSuite2#334]
When my animals reach full hearts, they don't show the petting symbol, even if I hadn't petted them that day. Could this maybe be a config option or something?

**Comment by tqdv** [comment]
It is !

If you're using the in-game menu, the option is named "Hide on max friendship", right under "Show when animals need pets".
If you're somehow using the per-save config file, then it's the 
  "HideAnimalPetOnMaxFriendship" key.

**Comment by CircusSeal** [comment]
Ohh, okay!! Thank you!! ^^

**Comment by CircusSeal** [comment]
Wait, hold on, how do I access the menu?

**Comment by CircusSeal** [comment]
Oh, it's the hammer-looking thing!

**Comment by tqdv** [comment]
I'm assuming you found the setting, so I'm closing this issue. Don't hesitate to open it again ;)
