### ISSUE TITLE
About the adaptation of the subsequent 1.6 version

### ISSUE THREAD

**Issue by TIESHU2004** [Annosz/UIInfoSuite2#368]
Will this mod be updated in the subsequent version 1.6 update?
If so, when will it be updated?

**Comment by ahoenerBE** [comment]
Hi @TIESHU2004 I'm planning on updating the mod to the latest SMAPI version over the next week. I expect there to be some hiccups but ideally it won't be that long after the release

**Comment by TIESHU2004** [comment]
What about the sinicization aspect of Chinese?

**Comment by drewhoener** [comment]
I have about half of the changes implemented over this weekend, hopefully I can get through the rest of it tonight to be ready for tomorrow.

**Comment by drewhoener** [comment]
> What about the sinicization aspect of Chinese?

Sorry, I don't think I'm familiar with what you're talking about, but I only speak english. If you'd like to help translate the mod, you're welcome to submit a translation PR

**Comment by TIESHU2004** [comment]
Updated to display Chinese interface.
