### ISSUE TITLE
Can't find smapi 4.0

### ISSUE THREAD

**Issue by DomitillePottier** [Annosz/UIInfoSuite2#370]
Hi !
I just downloaded ui info suite 2 in anticipation of the release of the Stardew valley 1.6 update
I updated smapi to the latest version and installed the mod correctly (this is not the first time I've done this).
However, I have a problem because the mod wants the smapi 4.0 version which I can't find anywhere, it seems it hasn't been released yet.
![image](https://github.com/Annosz/UIInfoSuite2/assets/55233473/ad074005-b167-420c-b25f-8ac6b5a83e0a)
Is it possible to remedy this issue?
Good evening,

**Comment by FunkMastaZ** [comment]
@DomitillePottier
here's a link to SMAPI 4.0.0: https://www.nexusmods.com/stardewvalley/mods/2400?tab=files
I hope this resolves your issue.

**Comment by drewhoener** [comment]
Please use the smapi link above, I understand there was some downtime before, but nexus should have what you need
