### ISSUE TITLE
Item Labels rendered at wrong layer when Game is zoomed out

### ISSUE THREAD

**Issue by Luna-Karch** [Annosz/UIInfoSuite2#374]
When hovering over an item in a chest, the community center bundle does show up for the item, but it shows up behind the current layer, which is a chest being open.

![image](https://github.com/Annosz/UIInfoSuite2/assets/96808999/76f133fc-8395-44b7-9bad-7d160ead5eac)

Also, I think it's supposed to shown the coin sell price here too but it doesn't.

My apologies if this is already being dealt with, I couldn't find an issue where it looked like it was.

**Comment by Luna-Karch** [comment]
Turns out it's a little more broken than I though, for parsnip it shows up like this

![image](https://github.com/Annosz/UIInfoSuite2/assets/96808999/c3ff65bd-ee1c-4a1f-8591-b3d8f64a4041)

**Comment by drewhoener** [comment]
@Luna-Karch I've been doing some testing as well, I thought I had it, but now when I load up my test save, it works just fine.
Do you have any information about exactly when it happens to help pin it down?
![image](https://github.com/Annosz/UIInfoSuite2/assets/6218989/dd0df119-1a85-492f-b104-50e32970d73e)

**Comment by Luna-Karch** [comment]
I should have provided steps to reproduce, My apologies. Although all I did was add the alpha release to my mods folder, I have no other mods, smapi version is 4.0.0

Would device specification help? 

This issue happened to me after opening a chest and hovering over an item that belonged in a community center bundle, whatever information you need I would be happy to provide

**Comment by Eiyame** [comment]
I can confirm this is a problem. This happens even if this is the only mod (besides smapi) installed. 

![20240319200312_1](https://github.com/Annosz/UIInfoSuite2/assets/164120831/3307b2b1-0b8f-4025-884e-90c8d9185e23)

**Comment by drewhoener** [comment]
It seems like this issue primarily happens when the zoom scale is below 100%. Working on figuring out why at this point

**Comment by drewhoener** [comment]
Related to PathosChild/StardewMods#844

**Comment by DavidGM91** [comment]
Also happens with different languages of the game
![image](https://github.com/Annosz/UIInfoSuite2/assets/44002792/a05e5cb2-e264-40a0-b6ee-19aa8d8e22ea)

**Comment by joshmitcho** [comment]
Agreed with other posters: Camera zoom causes it for some reason
