### ISSUE TITLE
Buffs change format of EXP Bar

### ISSUE THREAD

**Issue by pipqr** [Annosz/UIInfoSuite2#375]
I was at level 1 fishing when I ate a Sea Jelly, I believe, which adds Fishing +1 for 7m. When I caught my next fish, it showed the fishing exp bar as level 2 and the exp was -82/390. It counted down instead of up. I reached level 2 it continued, showing the bar as level 3 and the exp as -xxx/xxx. It went back to normal after the buff wore off, so I believe it is because of that. It didn't change my stats at all, but the formatting just changed.

**Comment by drewhoener** [comment]
This should be taken care of in the next version, if it isn't, please feel free to reopen
