### ISSUE TITLE
Luck icon, QoS icon, etc. stay on screen during cutscenes

### ISSUE THREAD

**Issue by pipqr** [Annosz/UIInfoSuite2#376]
All other UI icons disappear while the animation for bundle unlocks plays. The luck icon stays in its place.

**Comment by drewhoener** [comment]
Hi @pipqr, could you please provide a screenshot?

**Comment by pipqr** [comment]
> Hi @pipqr, could you please provide a screenshot?

I'm sorry, I didn't think to take one. I will take one next time I see it.

**Comment by PrincessRymna** [comment]
![ss](https://github.com/Annosz/UIInfoSuite2/assets/155788311/4ad9f82e-f25a-4a02-962b-24ea5a7c1678)
Here, I have a screenshot! :))

**Comment by laszlostark** [comment]
The same thing happens in the junimo cutscenes that play during the night when a room has been completed.

**Comment by Eiyame** [comment]
This also happens when placing items in the museum.

**Comment by pipqr** [comment]
I believe it happens with all cutscenes that remove the UI. It happens when you're placing buildings as well
![Untitled41_20240320000522](https://github.com/Annosz/UIInfoSuite2/assets/164086777/a1d638be-591b-46dc-a1b2-178ac627f8f2)
![IMG_9727](https://github.com/Annosz/UIInfoSuite2/assets/164086777/38526931-0c45-4079-b811-3737a8774bdf)

**Comment by SarahVanDenBerghe** [comment]
I also quickly want to add a comment as it's related. When hiding the UI (f4), the UI Info Suite icons remains visible as well. I assume fixing the above will also fix this, but just wanted to share this just in case!
