### ISSUE TITLE
scarecrow range not aligned

### ISSUE THREAD

**Issue by 3rrolB** [Annosz/UIInfoSuite2#377]
![20240320012852_1](https://github.com/Annosz/UIInfoSuite2/assets/164107927/3dfbfac5-dd79-480c-aa57-0907062d3979)

**Comment by calsyhoody** [comment]
this bug also happens to me 
![Uploading image_2024-03-20_094938364.png…]()

**Comment by pengxiangji** [comment]
我的洒水器也一样范围未对齐

**Comment by Luulu1u** [comment]
I know how to temporarily solve this problem. You just need to find the interface scaling ratio and scaling level in the settings, set them all to the same value, and you can display the normal range.

**Comment by pengxiangji** [comment]
> 我知道如何暂时解决这个问题。你只需要在设置中找到接口缩放比例和缩放级别，将它们全部设置为相同的值，就可以显示正常范围。

谢谢你感谢

**Comment by CyanRaven13** [comment]
I also found this issue on my sprinklers
![431664210_395634549941868_5533263980692290151_n](https://github.com/Annosz/UIInfoSuite2/assets/164184729/064520f7-aeb4-4512-b5c1-1094819e5764)

**Comment by drewhoener** [comment]
@3rrolB @CyanRaven13 could you please share your UI Scale and Game Zoom settings please? 
When I was testing it was at the correct offset, but my test world is at default zoom and scale.

**Comment by Luulu1u** [comment]
> 您能否分享一下您的 UI 缩放和游戏缩放设置？当我测试它时，它处于正确的偏移量，但我的测试世界处于默认缩放和缩放状态。Both are 75%

**Comment by tockity** [comment]
Same issue with Scarecrows. UI at 120 and Game at 75. Setting it to 120/100 fixes it, as does making the two the same.

**Comment by grlndgz** [comment]
I'm having a similar issue where the hover text isn't visible if the UI is zoomed either in or out. I think it's ending up behind the open inventory screen. I'm thinking it's the same thing because setting UI zoom back to 100% fixes it.

**Comment by 3rrolB** [comment]
@drewhoener indeed when everything is at a default 100% everything works but whenever you'd change the settings things tend to bugg

**Comment by Eliza543** [comment]
same issue for me, if my UI scale and game zoom don't match
