### ISSUE TITLE
item hover behind inventory

### ISSUE THREAD

**Issue by 3rrolB** [Annosz/UIInfoSuite2#378]
![20240320012910_1](https://github.com/Annosz/UIInfoSuite2/assets/164107927/5d4b73d6-97d2-49f8-8464-0e436901ba64)

**Comment by Cyanability** [comment]
Was just about to come here and say the same thing

**Comment by Zamiell** [comment]
@Cyanability please refrain from commenting unless you have something to add in order to prevent maintainers from getting spammed. otherwise use the emoji react feature!

**Comment by drewhoener** [comment]
Merging with #374
