### ISSUE TITLE
Smapi 4.0.0 not working

### ISSUE THREAD

**Issue by BublyWubly** [Annosz/UIInfoSuite2#379]
whenever i run the game with Smapi version 4.0.0 and the newest version of the mod it says it needs version 4.0.0 or later....

**Comment by GuiSaiUwU** [comment]
![image](https://github.com/Annosz/UIInfoSuite2/assets/107002177/6f11ba60-9091-4d1d-854e-855945a75109)
me too...

**Comment by Zamiell** [comment]
i think you two are on an old version, [this version](https://github.com/Annosz/UIInfoSuite2/releases/download/2.3.0-alpha-1/UIInfoSuite2.2.3.0-alpha-1.zip) works fine for me

**Comment by drewhoener** [comment]
There is a new version of SMAPI released with the new version of the game, please update to use this mod
