### ISSUE TITLE
SMAPI Error about "GameLoop.UpdateTicked event"

### ISSUE THREAD

**Issue by anapartu** [Annosz/UIInfoSuite2#382]
Seems to only happen in multiplayer to the farmhand, host has no errors
Farmhand SMAPI log: https://smapi.io/log/c5002b2ca6944fe7a2a8f589cbd0d50e

**Comment by drewhoener** [comment]
@anapartu Thank you for reporting, I'll have a fix out for this ASAP. 
Sorry for the issue

**Comment by drewhoener** [comment]
@anapartu This issue should be fixed in the next release. If it isn't please feel free to reopen this issue with a new log
