### ISSUE TITLE
Game crashes when chickens leave the coop after installing UI Info Suite

### ISSUE THREAD

**Issue by Waffie08** [Annosz/UIInfoSuite2#383]
I'm not sure if this is because of overlapping mods, or just because of Info Suit, but it did start when I added it to my game.
There are no problems with my game, up until I open the chicken coop on the Meadow Farm and my baby chickens come walking out.
My trees disappear, my game freezes and then crashes.

**Comment by drewhoener** [comment]
Closing as unverified. If you have a crash report or other actionable information, please feel free to open another issue
