### ISSUE TITLE
Mod skipped due to UIInfoSuite2.dll not existing

### ISSUE THREAD

**Issue by tessmcc** [Annosz/UIInfoSuite2#384]
[SMAPI-latest.txt](https://github.com/Annosz/UIInfoSuite2/files/14668103/SMAPI-latest.txt)
Sometimes I can restart and it works properly, but SMAPI is 90% of the time skipping UI Info Suite "because its DLL 'UIInfoSuite2.dll' doesn't exist." Error log attached.

**Comment by drewhoener** [comment]
Hi @tessmcc, I appreciate the log file. In the future, please use https://smapi.io log-parsing feature to provide a "pretty" link to your log. I've uploaded it myself for you this time
https://smapi.io/log/d22f893c64c943d2b286e645ea147271

**Comment by rayy210** [comment]
I have the same issue and redownloading did not solve it.

**Comment by rayy210** [comment]
Update: it works now! I downloaded the wrong file. 

I used the "wrong" copy from the following link: https://github.com/Annosz/UIInfoSuite2
I found the correct copy from the following link: https://github.com/Annosz/UIInfoSuite2/releases
if you scroll down to the bottom. 

Hope it helps.

**Comment by tessmcc** [comment]
Figured it out after a lot of gaslighting from my computer, turns out my anti-virus was deeming it a threat a removing it between me downloading and seeing that it was in the file and me opening SMAPI

**Comment by drewhoener** [comment]
haha incredible 😂
