### ISSUE TITLE
[1.6 Compatibility] [Bug]: Settings does not save

### ISSUE THREAD

**Issue by MrBeat93** [Annosz/UIInfoSuite2#390]
### Game Version

v2.3.0-alpha-2

### Multiplayer

Single Player

### Breaking Bug

Non-Breaking

### Visual Settings

UI Scale: 100%, Zoom: 100%

### Description

Changes in the settings will revert to default whenever I load a savefile in same game session or game restart.

**Comment by MrBeat93** [comment]
I noticed that the settings did saved after I slept.

**Comment by drewhoener** [comment]
With the current settings configuration, settings only save on day end. I'm sure this is inconvenient, but it is working as intended.
I intend to revisit configuration in the near future
