### ISSUE TITLE
[Bug]: New Weather Type is not Forecasted on Sidebar

### ISSUE THREAD

**Issue by biomagnet** [Annosz/UIInfoSuite2#403]
### Game Version

v2.3.0-alpha-2

### Multiplayer

Single Player

### Issue
Stardew 1.6 introduces a new type of weather occurrence: [Green Rain](https://kotaku.com/stardew-valley-green-rain-weather-update-1851353553). The mod doesn't check for if it's coming up, which admittedly gave me a big worry when it first showed up!

[Here's my save](https://github.com/Annosz/UIInfoSuite2/files/14676230/Luminescent_370553593.zip) waking up on the day it randomly happened to hopefully give more information.

**Comment by drewhoener** [comment]
This should be taken care of in the next version, if it isn't, please feel free to reopen

**Comment by biomagnet** [comment]
You're so fast! Thank you for all the work you're doing, by the way!!

**Comment by drewhoener** [comment]
@biomagnet If it's not too much trouble, could you just lmk if it actually shows up correctly? My testing world doesn't have all your mods so I couldn't load it unfortunately.

**Comment by biomagnet** [comment]
I was worried it'd be something like that. Let me check for you.

... Yep, looks good! 
![image](https://github.com/Annosz/UIInfoSuite2/assets/73308769/f7bd457c-3576-4146-b395-d6c99bb842ea)

**Comment by drewhoener** [comment]
awesome, thank you! :)
