### ISSUE TITLE
[Visual Bug]: Scarecrow range shows range misalignment

### ISSUE THREAD

**Issue by BoyAndDragon** [Annosz/UIInfoSuite2#405]
### Game Version

v2.3.0-alpha-2

### Multiplayer

Single Player

### Visual Settings

user interface scale：100%     Zoom：100%

### Description

![图片1](https://github.com/Annosz/UIInfoSuite2/assets/164279868/83060b33-2347-4e9c-bf71-c469df6a93cc)

**Comment by drewhoener** [comment]
Duplicate of #377
Fixed by #397
