### ISSUE TITLE
[Visual Bug]: more info display behind menu 

### ISSUE THREAD

**Issue by its3mm4** [Annosz/UIInfoSuite2#408]
### Game Version

v2.3.0-alpha-2

### Multiplayer

Single Player

### Visual Settings

UI Scale: 100% Zoom: 75%

### Issue

   Any time i hover over an item in my inventory when it is open the more information does not pop up infront of the inventory, instead it is behind. Noticable when you hover over items on the left side of the and you can see the part of the "more info" out the side of the menu

### Steps to Reproduce
1. Open inventory by clicking 'i'(im sorry idk how much info you want, i dont think yall are dumb i just want to make sure i describe it enough)
2. Hover over an item in the middle of your inventory, you won't see any popup
3. hover over an item on the very left column of your inventory and you will see the popup info peek out behind the menu.
4. Fourth

### Photo Example
![UiInfoSuite2](https://github.com/Annosz/UIInfoSuite2/assets/144840463/3b7d9ee7-a0f8-4e94-b2d1-ce27e4caf718)

**Comment by drewhoener** [comment]
This issue has been resolved by v2.3.0, which is out now: https://github.com/Annosz/UIInfoSuite2/releases/tag/v2.3.0

**Comment by its3mm4** [comment]
Thank you!
