### ISSUE TITLE
[Visual Bug]: Scarecrow outline off centre

### ISSUE THREAD

**Issue by its3mm4** [Annosz/UIInfoSuite2#409]
### Game Version

v2.3.0

### Multiplayer

Single Player

### Visual Settings

UI Scale: 100% Zoom: 75%

### Issue
 When the scarecrow is equiped the green overlay that shows it's range is off centre.
### Photo Example
![ScarecrowissueUIInfo2](https://github.com/Annosz/UIInfoSuite2/assets/144840463/adcfe5bf-b9f5-49aa-b9b2-52db7d046559)

### Steps to Reproduce
1. Equip scarecrow
2. Drag it around without placing it to observe that the green squares are off centre

**Comment by drewhoener** [comment]
This issue has been resolved by v2.3.0, which is out now: https://github.com/Annosz/UIInfoSuite2/releases/tag/v2.3.0

**Comment by its3mm4** [comment]
Thank you!!
