### ISSUE TITLE
Issue Tracker for v2.3.1

### ISSUE THREAD

**Issue by drewhoener** [Annosz/UIInfoSuite2#410]
## Issues for 2.3.1
- [x] #381 
- [x] #393 
- [x] #415
- [x] #428
- [x] #434

## Other PRs
- [x] #412

**Comment by Miktor89** [comment]
NPC Map locations are stuck on their home spawn locations and do not move as Mulitplayer player, not host. 
Single player NPC Map locations are correct and move. 
The host in the Multiplayer game is using the mod and the NPC Map locations work.
To summarize, NPC Map locations in multiplayer are broken for the players, but not the host. 

I have included a screenshot of my currently installed mods in case of conflict. The issue happened before the install of the Sprinting mod, to remove that as a possible conflict. 

![Screenshot 2024-03-27 085436](https://github.com/Annosz/UIInfoSuite2/assets/120998606/1df9af3b-c4cd-4d7d-8496-9c09130644e0)

**Comment by PK-Zira** [comment]
NPC Map locations is having major issues. While in Stardew Valley and tracking Harvey (you can not untrack him) it shows the location of Sandy. 
![Harvey Only](https://github.com/Annosz/UIInfoSuite2/assets/166630317/95925b56-9f26-487a-957d-e8c5e706ccd3)

When tracking Jodi it shows Evalyn's location.
![Harvy_Jodi](https://github.com/Annosz/UIInfoSuite2/assets/166630317/0426fd22-c262-4e5d-8357-d33495d1a8fc)

 If you go to the desert, you can unselect Harvey and it will hide Sandy, but now Jodi Tracks Lewis' location, and Lewis Tracks Perrie
![Jodi_Only](https://github.com/Annosz/UIInfoSuite2/assets/166630317/265b82db-7618-426d-96ec-09a19d03b0ec)
