### ISSUE TITLE
[Visual Bug]: sprinkler grid misaligned 

### ISSUE THREAD

**Issue by OneHappyChipmunk** [Annosz/UIInfoSuite2#411]
### Game Version

v2.3.0-alpha1

### Multiplayer

Single Player

### Visual Settings

UI Scale: 100% Zoom: 75%

### Steps to Reproduce
1. Zoom out or in
2. The highlight will slowly move out of alignment
![Screenshot (9)](https://github.com/Annosz/UIInfoSuite2/assets/164289381/3a971ace-e903-4942-a968-2f676b8b94a7)

****

**Comment by drewhoener** [comment]
This issue has been resolved by v2.3.0, which is out now: https://github.com/Annosz/UIInfoSuite2/releases/tag/v2.3.0
