### ISSUE TITLE
[Bug]: manifest.json

### ISSUE THREAD

**Issue by Sarahjaszczerska** [Annosz/UIInfoSuite2#416]
### Game Version

v2.3.0

### Multiplayer

Single Player

### SMAPI Log

no

### Steps to Reproduce
1. launch stardew with SMAPI 
2. it says UIInfosuite2-2.3.0 ebcause it contains files, but none of them are manifest.json
3. i have manifest.json installed but it says i dont have it
4. Fourth
![image](https://github.com/Annosz/UIInfoSuite2/assets/164375677/afd71504-39ef-4588-b436-53993a2150bd)

**Comment by drewhoener** [comment]
Closed as unverified, please check to make sure your files are in the correct location as shown in the screenshots above.
Also, check to make sure that your antivirus isn't deleting files from your downloads (or elsewhere), I've had a few people report things like that
