### ISSUE TITLE
[Breaking]: 'UIInfoSuite2.dll' doesn't exist

### ISSUE THREAD

**Issue by hwanbright** [Annosz/UIInfoSuite2#419]
### Mod Version

v2.3.0

### Multiplayer

Single Player

### SMAPI Log

https://smapi.io/log/d79f5995adab42318de11466fc87d153

### Steps to Reproduce
1. First
2. Second
3. Third
4. Fourth

**Comment by drewhoener** [comment]
Hi @hwanbright could this be similar to #384? The one user reported redownloading helped, and another noted that their antivirus was removing the file. I recommend checking both as I do provide the dll in the download
