### ISSUE TITLE
Include Github Update Key to manifest.json

### ISSUE THREAD

**Issue by Zefferis** [Annosz/UIInfoSuite2#42]
Hey there,

Since the nexusmod key 7098 isn't published, SMAPI can't actually check for updates which means if you're using the console or Mod Update Menu it just wont be *accurate* and users would need to manually check the github page for updates.

You can however add an update key that leads to your github releases:

https://stardewcommunitywiki.com/Modding:Modder_Guide/APIs/Update_checks

Hopefully that helps!

**Comment by Annosz** [comment]
Thank you! I know that with the not published Nexus mod it appears as an error, but I had no idea I can link my Github repo instead of the Nexus mod to the file, so this is a great help! :)

**Comment by Zefferis** [comment]
Fantastic, glad I could help ya out! -

I added a pull request to your repo, merging it (or editing the file yourself) should be the end of this github issue <3
