### ISSUE TITLE
[Visual Bug]: Calendar won't display event name

### ISSUE THREAD

**Issue by eggnoggins** [Annosz/UIInfoSuite2#424]
### Mod Version

v2.3.0

### Multiplayer

Single Player

### Visual Settings

UI Scale: 100%, UI Zoom: 100%

### Issue

    I'm not sure if this is a bug related to this mod or not and please correct me if I'm wrong, I could've pressed a button or something to disable this.
    
![image](https://github.com/Annosz/UIInfoSuite2/assets/48418469/21f68909-f910-4f97-a89e-36b164945a5a)

### Steps to Reproduce
1. Open calendar
2. Hover over date
3. Profit

**Comment by drewhoener** [comment]
Hey @eggnoggins 
I don't seem to have this issue on my testing world, are you using any other mods that might be impacting this? 
If you want to try and get to the bottom of it, maybe try starting a new world and adding mods until you can't see the event names anymore? You'd have to skip to winter, so maybe use CJB cheats

![image](https://github.com/Annosz/UIInfoSuite2/assets/6218989/297876d3-408c-4eda-89b6-c409508cccac)

**Comment by eggnoggins** [comment]
The birthday mod was the cause of the issue <:) ty for helping me
