### ISSUE TITLE
[Visual Bug]: Exit to Title duplicates rain/berry icons

### ISSUE THREAD

**Issue by BumblingBirdBrain** [Annosz/UIInfoSuite2#427]
### Mod Version

2.3.0

### Multiplayer

Single Player

### Visual Settings

100% 100%

### SMAPI Log

https://smapi.io/log/ec1479889e1f44959b18bed08d16d428

### Steps to Reproduce
1. Load save (salmon berry season/rain tomorrow)
2. Exit to Title
3. Load save
4. (I did this multiple times without crashing. See screenshot attached)

![downloadfile](https://github.com/Annosz/UIInfoSuite2/assets/164598776/1ba22357-6be0-4f5c-8eba-2f5f19ae0211)

**Comment by drewhoener** [comment]
Hey @BumblingBirdBrain it looks like you're on Linux from your log. 
I just fixed this a day or two ago in #387. I just need to put together a release. 
A quick fix is to go into the UiInfoSuite2 folder in mods and rename the folder `assets` to `Assets`
Sorry for the inconvenience

**Comment by BumblingBirdBrain** [comment]
Glad I didn't create more work for you then haha. Thank you for all of your time spent on this amazing mod!
