### ISSUE TITLE
[Visual Bug]: UI Info Suite tab off window in any other menu but the backpack

### ISSUE THREAD

**Issue by waterscaped** [Annosz/UIInfoSuite2#428]
### Mod Version

v2.3.0

### Multiplayer

Single Player

### Visual Settings

UI Scale: 100% Zoom Level: 75%

### SMAPI Log

https://smapi.io/log/47b31ccebe934188a274411767f76d15

### Description

Here is a link to a screenshot: https://imgur.com/a/gIJlhDG

**Comment by drewhoener** [comment]
Interesting, I don't currently do anything with the new animals menu but I'll take a look

**Comment by drewhoener** [comment]
Will be fixed in v2.3.1
