### ISSUE TITLE
[Bug]: Hotbar scrolling bug

### ISSUE THREAD

**Issue by vitorabdias** [Annosz/UIInfoSuite2#430]
### Mod Version

v2.3.0

### Multiplayer

Single Player

### Description

Well, i was playing after 1.6 install UI Info Suite 2 and a day after i installed my hotbar scroll stop working. I simply couldnt use the hotbar without using the keyboard numbers. I tried to restart the game, i unistalled and installed all my mods again but nothing seen to work. Then i created a new farm and i saw that the scroll was working fine, so i thought my save was corrupted. So i back a day before without UI Info Suite installed, and played this day and the next without any problem. So i think this glitch may be caused by UI Info Suite 2. I only have SDE, East Scarp (+ addons) and Cornucopia installed.

**Comment by drewhoener** [comment]
Hi there,
I haven't been able to reproduce this issue, have you tried removing mods to see if it's one of them? I've tested in my debug world and haven't found anything that could cause this. 
Please provide some detailed reproduction steps if possible

**Comment by drewhoener** [comment]
Closing as unverified, if you have proof & steps to reproduce, feel free to reopen
