### ISSUE TITLE
[Visual Bug]: "Pet your cat" hand indicator is not above the cat's head

### ISSUE THREAD

**Issue by GrizzleMacThrornBody** [Annosz/UIInfoSuite2#431]
### Mod Version

v2.3.0

### Multiplayer

Single Player

### Visual Settings

UI Scale: 90% Zoom: 75% Resolution: 1920x1080

### SMAPI Log

https://smapi.io/log/c42de0ee64df4bf8bb4ab6c084c9fa13

### Steps to Reproduce
1. First
2. Second
3. Third
4. Fourth

![IMG_4728](https://github.com/Annosz/UIInfoSuite2/assets/131812792/725d8dcb-66cf-4d0c-b112-eb4aa10cf050)

**Comment by Jualko** [comment]
Same thing happend with the turle pet for me. The petting icon moves with the pet (see picture 1 -> 2), but also with the camera when you move the player character (see picture 2 -> 3).

UI Scale: 100% Zoom: 75% Resolution:  2560 x 1440

![1](https://github.com/Annosz/UIInfoSuite2/assets/66382948/b76ae0dd-4808-48cf-8c67-fd67bf201245)
![2](https://github.com/Annosz/UIInfoSuite2/assets/66382948/524d5ce6-0ffa-4b4e-a883-fa236666cc15)
![3](https://github.com/Annosz/UIInfoSuite2/assets/66382948/8b413cd8-f738-4b33-b0fb-ee3d4e686880)
