### ISSUE TITLE
[Visual Bug]: Can't load sound file in linux

### ISSUE THREAD

**Issue by joeamaroq** [Annosz/UIInfoSuite2#432]
### Mod Version

v2.3.0

### Multiplayer

Single Player

### Visual Settings

UI scale: both 100%

### Issue

While playing the following error appears in SMAPI console:
[UI Info Suite 2] Error loading sound file from /home/xxxxx/.steam/debian-installation/steamapps/common/Stardew Valley/Mods/UIInfoSuite2/Assets/LevelUp.wav: Could not find a part of the path '/home/xxxxx/.steam/debian-installation/steamapps/common/Stardew Valley/Mods/UIInfoSuite2/Assets/LevelUp.wav'.

I think it occurs because in Linux pathnames are case sensitive and the app looks for a folder 'Assets' with a capital 'A'. In the actual downloaded zip-file for the mod, the folder is called 'assets' with a lower case 'a'.

**Comment by drewhoener** [comment]
Hey @joeamaroq, thanks for reporting.
I've had a few people bring this up while I get ready for the next release, please check out #427.
Thanks
