### ISSUE TITLE
[Bug]: Tea Sapling Issues

### ISSUE THREAD

**Issue by rina0503** [Annosz/UIInfoSuite2#434]
### Mod Version

v2.3.0

### Multiplayer

Single Player

### SMAPI Log

 https://smapi.io/log/59777d7ea8cf41139ac76d9536306430

### Steps to Reproduce

Planting Tea Sapling
Or
Tea Sapling Approaching

**Comment by drewhoener** [comment]
Will be fixed in v2.3.1
