### ISSUE TITLE
[Visual Bug]: Bundle Info not appearing for some items

### ISSUE THREAD

**Issue by Wagbag** [Annosz/UIInfoSuite2#438]
### Mod Version

v2.3.0

### Multiplayer

Single Player

### Visual Settings

UI and Zoom is 100%

### Issue

I'm at the start of the game and I am getting bundle info for Spring Foraging items, but that is it for right now. I have river fish that are needed for a bundle, and spring crop bundle, but the bundle info is not there for those when you hover over those items. 

### Steps to Reproduce
1. Just have items for fish or spring crops, along with spring foraging items, and you should see the lack of a hover over UI element for the fish and crops. For me, the Spring Forage info shows up fine. 

![20240324145357_1](https://github.com/Annosz/UIInfoSuite2/assets/20648000/1a3eeb36-f5b5-49e0-b0d2-1016b75294f5)
![20240324145352_1](https://github.com/Annosz/UIInfoSuite2/assets/20648000/e3f6820c-76ac-4336-a141-2873f9b51dbc)
![20240324145355_1](https://github.com/Annosz/UIInfoSuite2/assets/20648000/279592ad-046f-4589-b4c7-40a8e0e53551)

**Comment by drewhoener** [comment]
Hi @Wagbag, this is actually the intended functionality, only bundles/scrolls that are physically in the community center are shown. 

Duplicate of #373

**Comment by Wagbag** [comment]
I was about to come back here and delete this because, yes, the bundles had not been unlocked yet. Sorry about that :)
