### ISSUE TITLE
[Bug]: Bundle requirements are revealed before player can read Junimo text

### ISSUE THREAD

**Issue by taylorjwalker** [Annosz/UIInfoSuite2#444]
### Mod Version

v2.3.1

### Multiplayer

Single Player

### Issue
Crafts Room bundle requirements are revealed prematurely in `UIInfoSuite2/UIElements/ShowItemHoverInformation.cs`.

In order to access requirements for the first group of bundles (in the Crafts Room), the player must first trigger the initial Community Center cutscene and complete the "Rat Problem" and "Meet the Wizard" quests. After completing the "Meet the Wizard" quest, the Wizard gives the player a potion that allows them to read the language of the Junimos.

**Comment by drewhoener** [comment]
Makes sense to me. Also removes the inconsistency where people have been reporting that bundles weren't displaying properly when they hadn't been unlocked yet

**Comment by Udoachim** [comment]
This is also case with the Missing Bundle. It shows up in UI Info Suite before the bundle is available in the abandoned Joja market.

**Comment by taylorjwalker** [comment]
@Udoachim, assuming #445 doesn't fix the Missing Bundle issue, please open a new issue with more specific details (when it's showing up in UIInfoSuite2, when it should be available, etc.). Then I'd be happy to take a look.
