### ISSUE TITLE
[Visual Bug]: Tea Sapling tooltip incorrectly shown on other crops

### ISSUE THREAD

**Issue by WTWX2** [Annosz/UIInfoSuite2#447]
### Mod Version

v2.3.0

### Multiplayer

Single Player

### Grape seedlings turn into Tea Saplings

**Comment by drewhoener** [comment]
??????

**Comment by WTWX2** [comment]
This might be from another mod conflict but i’m not sure, once i’m free i’ll try test and figure out what this is caused by and if it isn’t related to this mod i’ll close this

**Comment by WTWX2** [comment]
![image](https://github.com/Annosz/UIInfoSuite2/assets/163057455/7d22c20f-1004-4538-b45c-03b6c4f68a26)

**Comment by drewhoener** [comment]
Oh I see!
Not the actual item just the tooltip. 
Thanks!

**Comment by WTWX2** [comment]
![image](https://github.com/Annosz/UIInfoSuite2/assets/163057455/441f70f1-746c-4df1-81d5-c6494ef755e5)

Yeah i think it might be related to the More Crops mod but im not 100% sure

**Comment by drewhoener** [comment]
Is this crop added by More Crops?

**Comment by WTWX2** [comment]
Yeah i think this could be an issue with the More Crops mod and not your mod, sorry about that.

**Comment by drewhoener** [comment]
Which crop is it? I'd like to test, the mod should work properly with all the crops

**Comment by WTWX2** [comment]
Its the grape planter

**Comment by drewhoener** [comment]
Grapes are part of the base game, weird

**Comment by drewhoener** [comment]
![image](https://github.com/Annosz/UIInfoSuite2/assets/6218989/0fc98f0c-6248-4b4e-a516-4f7fa580fb03)
Will be added next version
