### ISSUE TITLE
[Visual Bug]: Color advice

### ISSUE THREAD

**Issue by 18796993096** [Annosz/UIInfoSuite2#448]
### Mod Version

v2.3.1

### Multiplayer

Multiplayer (Host)

### Visual Settings

100%   100%

### Steps to Reproduce
1Fist:The color of the working range of the device is too thick, especially when the working range of multiple devices is stacked on top of each other, the color will block the entire screen, so that you can't see anything else.
2second:I wish the colors were a little more transparent.
3third:It would be better if some special optimization could be made for the overlapping of multiple equipment working ranges。
4fourth:Alternatively, add a feature that allows the player to freely adjust the transparency of the color.

![61ad9d881ffda7c11b250cc5d3d6da2e](https://github.com/Annosz/UIInfoSuite2/assets/35052931/aa37f633-0c22-4768-b201-c56b82000fde)
![174a1ac4f3062188057a2d415d3bee4b](https://github.com/Annosz/UIInfoSuite2/assets/35052931/8f73dc00-db89-4970-b4a3-86f25d64e30b)

**Comment by drewhoener** [comment]
Hey @18796993096 
This is a great suggestion, for sure something we've had comments on in the past. 
I'll work on implementing these suggestions into a later version
