### ISSUE TITLE
[Feature]: custom bush mod compatibility

### ISSUE THREAD

**Issue by n-marcelino** [Annosz/UIInfoSuite2#450]
### Description

Hello! Any chance for compatibility with [custom bush](https://www.nexusmods.com/stardewvalley/mods/20619)?

It's a framework which allows custom bushes to be added to the game which work like the tea sapling.

The mods that use it (cornucopia) adds lots of new stuff, but UIInfoSuite2 labels all of it as tea sapling even if it isn't.

**Comment by drewhoener** [comment]
Seems to be related to #447, I'll work on getting it fixed

**Comment by drewhoener** [comment]
![image](https://github.com/Annosz/UIInfoSuite2/assets/6218989/b11be0d4-3142-480f-937f-b26a90099a8e)
Will be added in the next version
