### ISSUE TITLE
[Visual Bug]: working range isnt transparent

### ISSUE THREAD

**Issue by HongHuangTY** [Annosz/UIInfoSuite2#454]
### Mod Version

v2.3.1

### Multiplayer

Single Player

### Visual Settings

100 75

### SMAPI Log

no red

### BUG sometime working range is transparent, sometime not, and the color is too thick i cant see where my crops clearly
thank ur mod no matter what
![0740a69c32de30fb5296079078314999](https://github.com/Annosz/UIInfoSuite2/assets/101971140/cd5025c1-17db-4cfd-bd8c-469dc2e204a6)

**Comment by HongHuangTY** [comment]
wait, idk why the last sentence isnt bold and too small, im so sry

**Comment by drewhoener** [comment]
Thank you for reporting, this is on the roadmap and I'll try and get it in soon :)

**Comment by HongHuangTY** [comment]
> Thank you for reporting, this is on the roadmap and I'll try and get it in soon :)

thank u so much
