### ISSUE TITLE
[Bug]: Mouseover items in inventory does not work for Bundles items

### ISSUE THREAD

**Issue by j3nesis87** [Annosz/UIInfoSuite2#455]
### Mod Version

v2.3.1

### Multiplayer

Single Player

### SMAPI Log

https://smapi.io/log/c47b2c28969c40f69228be6e0016d222

### Issue

The mouseover to show info function from the inventory (e.g. showing whether an item is required for a Bundle) is not working. Other functionality, such as the Luck indicator and mouseover crops to show time to harvest, does work. This seems to happen particularly when using custom Bundles.

### Steps to Reproduce
1. Have a bundle mod installed e.g. More Challenging Community Bundles
2. Mouse over item in player inventory
3. Tooltip 'Item needed for Bundle x' should appear, it does not
4. SMAPI shows errors

**Comment by drewhoener** [comment]
Thanks for the log, it looks like I'm failing to parse something about the bundle data. I actually have an unrelated rework for bundle code on the way that might accidentally fix this.
