### ISSUE TITLE
Request: Controller support

### ISSUE THREAD

**Issue by HalfEnder776** [Annosz/UIInfoSuite2#47]
At the current moment it's not possible to go to the mod's settings, calendar or billboard while using a controller. If it's not possible to change what the cursor snaps on to i would suggest adding a config file  for setting key binds for each of the windows.

Btw thanks for updating this mod, it helps a lot.

**Comment by Deflaktor** [comment]
As a workaround you can use https://www.nexusmods.com/stardewvalley/mods/492 (and optionally https://www.nexusmods.com/stardewvalley/mods/9295)
