### ISSUE TITLE
[Breaking]: can't open any save file without crashing

### ISSUE THREAD

**Issue by liananoelle** [Annosz/UIInfoSuite2#483]
### Mod Version

v2.3.1

### Multiplayer

Single Player

### SMAPI Log

https://smapi.io/log/b4b85616534e4aed93c29af29cccbf61

### Description

i realized i had an old version installed and it wasn't working so i deleted it from my mods and put in the newest one but it makes me crash every time. i can boot up stardew valley fine but as soon as i select a save file to play it crashes with the message shown below; i know it has to be this mod since its fixed as soon as i removed it, and it can't be another mods fault as i tried removing literally every other mod and it still happened. how do i fix this??

![image](https://github.com/Annosz/UIInfoSuite2/assets/167482667/ad47a367-f95a-4289-a8f0-de44eb487a4e)

**Comment by drewhoener** [comment]
I've never seen this message before, and I can't find anything in the logs that mentions it's me...
Have you tried updating all your mods, I can see several others with new versions

**Comment by liananoelle** [comment]
> I've never seen this message before, and I can't find anything in the logs that mentions it's me... Have you tried updating all your mods, I can see several others with new versions

i can try, but considering this still happened when all my other mods were removed im not sure if it'll fix it

**Comment by drewhoener** [comment]
I've never seen it either. It's possible that it could be something with the latest 1.6.4 release. I might recompile it later tonight.
I also notice you're several versions behind on SMAPI

**Comment by VladimirMarkelov** [comment]
Update SMAPI to `4.0.7` - it solves a lot of crashes after updating SDV to `1.6.4`. E.g, without updating SMAPI the mod NPCMapLocations also crashes SDV 1.6.4

**Comment by liananoelle** [comment]
> Update SMAPI to `4.0.7` - it solves a lot of crashes after updating SDV to `1.6.4`. E.g, without updating SMAPI, other mods like NPCMapLocations also make SDV 1.6.4 crash

that seemed to have fixed everything, ty!!!!
