### ISSUE TITLE
UI2 Not effective

### ISSUE THREAD

**Issue by 13947312448** [Annosz/UIInfoSuite2#485]
### Mod Version

2.3.1

### Multiplayer

Single Player

### SMAPI Log

https://smapi.io/log/80f5a8c411b543a8a9e17168d5627ed8

### Description

UI2 Not effective

**Comment by JokerBTA** [comment]
Looks like UI Info Suite 2 needs updating

**Comment by drewhoener** [comment]
SMAPI is out of date and will not function with stardew 1.6.4.
