### ISSUE TITLE
[Feature]: PLEASE add a config.

### ISSUE THREAD

**Issue by rokukou** [Annosz/UIInfoSuite2#488]
### Description

Please add a config perferably supported by generic mod config menu. This mod is very annoying to use with all the features, even a basic enable/disable certain features would be good.

**Comment by drewhoener** [comment]
Hi there!
This mod already provides a config in the ingame menu, which should provide (almost) all the features as toggles.
If this is not enough, you can feel free to edit your config files in `$(ModFolder)\UIInfoSuite2\data\$(configName).json`.
More detailed support for GMCM is planned for the future
