### ISSUE TITLE
[Breaking]: 

### ISSUE THREAD

**Issue by DrowningDucks** [Annosz/UIInfoSuite2#490]
### Mod Version

v2.3.2

### Multiplayer

Single Player

### SMAPI Log

 Found 7 mods with warnings: [SMAPI]    Skipped mods [SMAPI]    -------------------------------------------------- [SMAPI]       These mods could not be added to your game.  [SMAPI]       - UI Info Suite 2 2.3.2 because its DLL 'UIInfoSuite2.dll' doesn't exist.

### Description

Hi! just tried downloading the latest version but it won't load because the DLL is missing. I've redownloaded it twice but still the same message every time. 
![image](https://github.com/Annosz/UIInfoSuite2/assets/167606170/1f75dc1b-348b-4922-95c7-d5d24a0ce35c)

**Comment by drewhoener** [comment]
This is usually an issue with your antivirus, please make sure that it's not being removed by your computer

**Comment by VladimirMarkelov** [comment]
MS Defender built-in in Windows 10 even refuses to download the latest release `2.2.3.2`. It complains about `Trojan:Script/Wacatac.H!ml` :(

**Comment by drewhoener** [comment]
It also has this false positive for mods like SpaceCore and ContentPatcher, you'll have to tell windows to stop removing it.

**Comment by VladimirMarkelov** [comment]
Yes, it helps and it is not the first time an antivirus tampers with legitimate updates.
