### ISSUE TITLE
[Breaking]: The new version of UI2 conflicts with Ultimate Fertilizer

### ISSUE THREAD

**Issue by Jumping-notes** [Annosz/UIInfoSuite2#493]
### Mod Version

v2.3.2

### Multiplayer

Single Player

### SMAPI Log

https://smapi.io/log/15a09807065e4d59b1f9d736605e028f

### Steps to Reproduce
1.When the mouse moves over the overlapping fertilizer, no information is displayed and errors are reported frantically.

**Comment by drewhoener** [comment]
Hi! Could you tell me which fertilizer you put on your plants so I can test?

**Comment by mmm4899** [comment]
I also encountered this problem.
I spilled top-grade water retention and high-grade fertilizer.
Here is my SMAPI link.
https://smapi.io/log/8a6232f84e0e4c4897e8ef4edef46cf0

**Comment by mmm4899** [comment]
I suspect that it has nothing to do with the type of fertilizer, because the information can't be read normally or the information can't be recognized, which leads to errors.

**Comment by Inny78** [comment]
Same here with 2.3.3:
[UI Info Suite 2] This mod failed in the Display.RenderingHud event. Technical details:
NullReferenceException: Object reference not set to an instance of an object.
   at UIInfoSuite2.UIElements.ShowCropAndBarrelTime.OnRenderingHud(Object sender, RenderingHudEventArgs e) in C:\Users\Drew\RiderProjects\DH-UIInfoSuite2\UIInfoSuite2\UIElements\ShowCropAndBarrelTime.cs:line 335
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101

**Comment by THE-Mr-goat** [comment]
Same situation.But the previous version UI2 could display crop information with Ulimiate Fertilizer.

**Comment by drewhoener** [comment]
@THE-Mr-goat @Inny78 @mmm4899 Will be fixed in the next released version
![image](https://github.com/Annosz/UIInfoSuite2/assets/6218989/1981161f-af1d-4219-a6b1-c74054d4db31)
