### ISSUE TITLE
[Visual Bug]: Multilayer map show overlap villager name and icon

### ISSUE THREAD

**Issue by Jackson11500** [Annosz/UIInfoSuite2#497]
### Mod Version

v2.3.2

### Multiplayer

Single Player

### Visual Settings

UI Scale:100%| Zooms:75%

### [Visual Bug]: Multilayer map show overlap villager name and icon

![image](https://github.com/Annosz/UIInfoSuite2/assets/55009845/e71ca1f2-bf78-4683-a0dc-4899a051eb48)
![image](https://github.com/Annosz/UIInfoSuite2/assets/55009845/206f0607-5a8c-4331-9b8d-3d2d65ca6ce9)

### Steps to Reproduce
1、install mods with multiple layer maps like Ridgeside Village
2、open maps
3、the villager with original map(stardew valley) are overlap with ridgeside villager, including their name and icon

**Comment by drewhoener** [comment]
UIInfoSuite2 map tracking will no longer conflict with RSV map in next version
