### ISSUE TITLE
[Breaking]: Mod is not working.

### ISSUE THREAD

**Issue by Nanmiint** [Annosz/UIInfoSuite2#499]
### Mod Version

v2.3.2

### Multiplayer

Single Player

### SMAPI Log

https://smapi.io/log/b74ff097b4b44825a01893a0266675d4

### Before the 1.6.4 update this mod worked, but after the update it`s not.
![Screenshot 2024-04-21 130755](https://github.com/Annosz/UIInfoSuite2/assets/167679953/7d6b46ae-773c-434c-bc21-9f5746cad361)
![Screenshot 2024-04-21 130654](https://github.com/Annosz/UIInfoSuite2/assets/167679953/d6e1e2c5-9a30-4fcd-9302-b8d4e1d3bfc4)
![Screenshot 2024-04-21 130724](https://github.com/Annosz/UIInfoSuite2/assets/167679953/d4b4b62a-7735-4540-b159-be2b5816a927)

**Comment by JokerBTA** [comment]
SMAPI is outdated, updated it and it should be fine.

**Comment by Nanmiint** [comment]
> SMAPI is outdated, updated it and it should be fine.

OMG TYSM
