### ISSUE TITLE
[Visual Bug]: UI on-screen during Night Market Mermaid Show

### ISSUE THREAD

**Issue by honeyarsonist** [Annosz/UIInfoSuite2#508]
### Mod Version

v2.3.2

### Multiplayer

Single Player

### Visual Settings

UI Scale: 145% Zoom: 170%

### Steps to Reproduce
1. Uhh? Visit the night market and get a coffee
2. visit the merma
![Screenshot 2024-04-27 042601](https://github.com/Annosz/UIInfoSuite2/assets/148876054/8803a18c-918f-4cbb-a8c6-c3caac3e67c7)
id boat, cut scene starts
3. Third
4. Fourth

**Comment by drewhoener** [comment]
@honeyarsonist The clock and toolbar are still on screen, so it meets the requirements for the UI icons to be there. If the toolbar was gone, then the icons would be as well

**Comment by drewhoener** [comment]
Closing as unverified
