### ISSUE TITLE
[Visual Bug]: Can't see how long do crops takes

### ISSUE THREAD

**Issue by rns531** [Annosz/UIInfoSuite2#514]
### Mod Version

2.3.2

### Multiplayer

Single Player

### Visual Settings

both 90%

### SMAPI Log

https://smapi.io/log/eccf67d3686c41a184d5f71bbdf77530

### Steps to Reproduce
1. First
When I go to the farm whtich has crops, these errors happened.
As you can see, I can't see nothing.
![20240430223331_1](https://github.com/Annosz/UIInfoSuite2/assets/129955361/e729397a-c45e-439a-aa5c-42f1466bb974)

2. I think this happen because of 'Ultimate Fertilizer' mod (https://www.nexusmods.com/stardewvalley/mods/21318)
Those crops which can't see have 2 fertilizers.

**Comment by drewhoener** [comment]
Ultimate Fertilizer bug is known, and a fix is coming later this week
