### ISSUE TITLE
Make this the official UIInfoSuite on smapi.io/mods

### ISSUE THREAD

**Issue by chrisheib** [Annosz/UIInfoSuite2#52]
Hey there, it took me a while and a detour through cdaragorns pull requests to find this better version of the info suite. 
The old one doesn't seem to take in pull requests anymore, as you apparently already noticed.
You might want to make an account in the StardewValleyWiki, set the info suite to deprecated (⚠) and add yours as UIInfoSuite 2 or similar on https://stardewvalleywiki.com/Modding:Mod_compatibility 

That way players can find it easily.

Thanks for keeping this going :)

**Comment by thecosmicslug** [comment]
I only found out about this fork yesterday, I assumed the old one was still being maintained.

**Comment by Annosz** [comment]
Well thats a hard question - I originaly started this mod as a replacement for the old UI Info Suite, but before I was able to publish it, the original author reappeared. We talked, and it was clear that he does not wish to abandon his project, and I want to respect this.

Of course it's hard if he says it but then he does not receive pull request for another 4 months again - but so far I want to keep his wish in respect. So I do not wish to mark my mod as an official or as a replacement on any platform :)

**Comment by chrisheib** [comment]
@Annosz Thats a good point, thanks for answering.

I suggested this because at the moment, THIS is the working mod, while the other one is objectively broken. 

I like the idea to wait a few more months. It's his hard work in the first place.

**Comment by rikai** [comment]
I think the good compromise here is the releases section of GitHub.

I know I've been pointing a number of people from the SDV discord over there to try this version when they were looking for fixes to the original mod. 👍

**Comment by pepoluan** [comment]
If the official is _certifiably broken_, then adding a "workaround" note on smapi.io/mods should be okay.

After all, it's easy to revert the note if the official mod is updated again.

**Comment by n1spro** [comment]
the author of the original mod is still not active at all ...

**Comment by adroslice** [comment]
This version needs more exposure, and at least listing it on smapi.io is the best way. I only now rediscovered it after having forgotten about it.

**Comment by thecosmicslug** [comment]
indeed, I agree. I keep finding people asking about UIInfoSuite, and they are always surprised when I direct them to this project.

**Comment by Annosz** [comment]
I just realized that somebody already uploaded this mod to smapi.io and added a link as official replacement, so I will be closing this issue for now.
