### ISSUE TITLE
[Visual]: Using this mod on multiplayer causes the mod to break if other users in game menu aren't the same.

### ISSUE THREAD

**Issue by GitFist** [Annosz/UIInfoSuite2#520]
### Mod Version

v2.3.1

### Multiplayer

Multiplayer (Host)

### SMAPI Log

https://smapi.io/log

### Issue
![image](https://github.com/Annosz/UIInfoSuite2/assets/117530804/83800d46-da5e-46b5-bf5b-365cdbc9842b)
I have most of the features on this mod disabled as the host. The other users on my server have the mod with features enabled. My settings are overruled by their settings. A simple config file in the mod folder would fix this since farmhands could receive the mod file from me.

### Steps to Reproduce
1. First
2. Second
3. Third
4. Fourth

**Comment by drewhoener** [comment]
@GitFist Just to confirm, if the other players in your game turn off the luck display, it correctly disables? This shouldn't be a thing, since nothing gets synced over the network, each instance is the same.

**Comment by GitFist** [comment]
> @GitFist Just to confirm, if the other players in your game turn off the luck display, it correctly disables? This shouldn't be a thing, since nothing gets synced over the network, each instance is isolated

Thanks for the reply. I think there was confusion on how the mod was supposed to operate. I added this mod to an existing save and after configuring in game during multiplayer none of the changes worked because there wasn't a JSON generated in the /data/ folder until I slept and closed the game.

Is it possible to have a config file that overrules any JSON file? If not that's fine since I know how the mod works now.

**Comment by drewhoener** [comment]
@GitFist
> Is it possible to have a config file that overrules any JSON file? If not that's fine since I know how the mod works now.

Yes, if you use GMCM or edit config.json, you can specify a config name to use all the time

**Comment by drewhoener** [comment]
Closing this issue since it's stale, but I hope to be moving fully to GMCM in the future :)
