### ISSUE TITLE
UI Info Suite 2 breaking audio upon loadout[Breaking]: 

### ISSUE THREAD

**Issue by juicieorange** [Annosz/UIInfoSuite2#527]
### Mod Version

v2.3.2

### Multiplayer

Single Player

### SMAPI Log

https://smapi.io/log/4fac1e620bd54725ab071a24565f05d5

### Description

Using Vortex, the mod manager, I have multiple mods from Nexus and then UI info Suite2, taken directly from Github and uploaded into my mods. 

Upon starting the game with mods, I receive this error and red text from SMAPI about my audio not initializing. I can confirm I receive no game audio. 

Disabling UI Info Suite 2  in Vortex resolves any sound issue I have. 

*only getting sound issues with Stardew Valley. I checked headphones, youtube, spotify, etc for other audio issues.* 

![Screenshot 2024-05-09 174800](https://github.com/Annosz/UIInfoSuite2/assets/169404390/f3c4fb2b-4401-4a71-9181-48fce149265b)

### Steps to Reproduce
1. Enable mods & UI Info Suite 2
2. Press Play (load the game) 
3. Inspect SMAPI loadout and see if red text is displayed

**Comment by JokerBTA** [comment]
Vortex is not recommended for mod managing. It tends to mess up files. An option would be Stardrop which was made specifically for Stardew Valley modding.

**Comment by drewhoener** [comment]
It doesn't look like you've provided your entire log, but it does look like the game errors out on sound initialization before UIInfoSuite even starts, then there's an error when it tries to register its sound with the game. I'd look into that.
Also echoing what Joker said above, try stardrop if able

**Comment by drewhoener** [comment]
https://forums.stardewvalley.net/threads/world-doesnt-load-up-help.10560/
Maybe related? Same error at the beginning

**Comment by juicieorange** [comment]
this was an extremely weird issue, but i have come back to say the issue isnt UI info suite 2. You can close this! tl;dr - other audio settings were the issue (very hard to find lol)
