### ISSUE TITLE
[Visual Bug]: No Petting Hands

### ISSUE THREAD

**Issue by SnaileeKai** [Annosz/UIInfoSuite2#540]
### Mod Version

v2.3.3

### Multiplayer

Single Player

### Visual Settings

UI Scale: 100% Zoom: 100%

### Issue
 There is no hand to tell me which chickens/cows need to be pet. It is only showing on my sheep, dinosaurs, and rabbits.

### Steps to Reproduce
1. First load the game
2. Second go to a barn/coop
3. Third see there are no hands telling you which animals have not been pet

**Comment by SnaileeKai** [comment]
I am so sorry I put the wrong version. I am using UI Info Suite 2.3.3

**Comment by SnaileeKai** [comment]
@drewhoener Hi! I just double checked and made sure I have the most up to date Stardew Valley, Smapi, and Ui Info Suite 2, and the screen shots below are what it looks like when I walk in to the barn/coop on my farm. No errors were showing on the log which is odd. Thank you for your time and response :)

![Barn](https://github.com/Annosz/UIInfoSuite2/assets/170346580/fcf33fae-ac85-4b99-b897-2957dc40dd4c)
![Coop](https://github.com/Annosz/UIInfoSuite2/assets/170346580/6968ebcc-7bae-4e27-9e3f-07f49476de03)

**Comment by drewhoener** [comment]
@SnaileeKai I can see a hand on one of your chickens on the second screenshot. Is it possible that the other animals have full friendship? There's an option that turns off the hand once they reach full hearts

**Comment by drewhoener** [comment]
If you'd like to always be able to see the hands, you can turn off "hide on max friendship"
![image](https://github.com/Annosz/UIInfoSuite2/assets/6218989/38137938-d9a9-4bd4-8b61-0dac6489bcb0)

**Comment by SnaileeKai** [comment]
@drewhoener That was definitely the issue! I didn't realize my animals and I had become such good pals! Thank you for your help! I did not know about these settings before now
