### ISSUE TITLE
[Visual Bug]: All tilled tiles say "Weeds" and tiles with crops on them say "with weeds"

### ISSUE THREAD

**Issue by ER-95** [Annosz/UIInfoSuite2#548]
### Mod Version

Current

### Multiplayer

Single Player

### Visual Settings

Default

### SMAPI Log

https://smapi.io/log/fcb14b042ad94a8ea3bedd7066e49ab5

### Issue
![StardewModdingAPI_UWMRVzp9f0](https://github.com/Annosz/UIInfoSuite2/assets/53078703/c412b297-fe51-49c5-b3d7-ee5e48155da3)
![StardewModdingAPI_7By3nB8MC5](https://github.com/Annosz/UIInfoSuite2/assets/53078703/65bb958d-9f85-4afe-bcb4-354379b8840f)

### Steps to Reproduce
1. Install UIInfoSuite2
2. Load an existing save game
3. Hover over any tilled or planted tile

**Comment by drewhoener** [comment]
@ER-95 interesting, this looks like the fertilizer overlay popping up but it says weeds... 
do you have a mod that adds weeds? Maybe they're using the fertilizer field for that by default and I'm showing it

**Comment by drewhoener** [comment]
Granted, most of my recent testing has been with fertilizer on crops, maybe I messed something up

**Comment by ER-95** [comment]
@drewhoener I don't have any mods that adds weeds, no - and the issue persists even if I remove all of my other mods except UIInfoSuite. Someone else in the Stardew Valley Discord said they were having the same issue but couldn't figure out why either.

It only occurs on tiles that have been tilled for a while - if I freshly till a tile (or if I untill and retill a tile that says "Weeds" on it), the notice doesn't appear.

If there's any other info I can provide please do let me know!

**Comment by drewhoener** [comment]
@ER-95 It's probably me then... could you try putting fertilizer on and see if changes to fertilized?

**Comment by ER-95** [comment]
@drewhoener It changes to "Basic Fertilizer" on a tilled plot with no seeds, yep!

**Comment by drewhoener** [comment]
@ER-95 Do you know approx how much time it takes for the plot to change to weeds so I can test?

**Comment by ER-95** [comment]
@drewhoener I have absolutely no idea I'm afraid! Definitely less than 10 days, but I'm not sure of the exact number.

**Comment by ER-95** [comment]
If it helps, this is my save file - if you leave the house, the affected tiles are directly beneath you
[Uploading SleepyBaby_366165213.zip…]()

**Comment by ER-95** [comment]
Hi @drewhoener - is the mod safe to use while this text appears? i.e. is it just a visual bug or will it impact what I'm harvesting? Many thanks

**Comment by drewhoener** [comment]
@ER-95 Downloaded your save. Those tiles had id "0" for fertilizer, which corresponds to the "weeds" item.
Can't say *how* that happened, since I've never seen it and I couldn't reproduce it with your save, but I added a special case for it. It'll be in the next update :)
