### ISSUE TITLE
Stop info icons from getting stuck behind quests button?

### ISSUE THREAD

**Issue by gainem** [Annosz/UIInfoSuite2#56]
After the quest list has been emptied and the **[ ! ]** tab disappears from the UI, the luck and other icons are all nudged to the right into its place. But once new jobs are accepted and the tab reappears, the icon positions are not reset and they render behind it. Saving and starting the next day does not reset their position either, as far as I have seen.

**Comment by Annosz** [comment]
Sorry, probably should have looked into this earlier. However, now I can't reproduce the issue, the icon positions are reset for me when the [ ! ] tab reappears. Can you confirm that the bug is still happening?

**Comment by chocoashlim** [comment]
Hello! I'm not the original poster of this issue so I hope it's okay to comment that I also currently still have this bug. Also, thank you so much for making this mod and continuing to update it, you are an absolute godsend!

**Comment by VashtiH** [comment]
Hello!  I'm not the original poster of this, but can confirm that I still have this bug, or at least something like it.  As a note, it only happens in cases where the only active quests are quests added in the 1.5 update, such as the special orders board or Mr. Qi's special orders board.  Quests that existed prior to that update still shift the icons as expected, including if they're sharing the journal with 1.5 quests; but the newer quests will result in the [ ! ] icon displaying over any other icons.

**Comment by Annosz** [comment]
@VashtiH thanks for the clarification, it is likely that I was not able to reproduce the issue because of this. I will look into it again. Also, thanks for the kind words!

**Comment by livinginfictions** [comment]
Hello, I dont mean to be a bother, and I know you said you were working on it, just wondering if there was any update on this bug fix?

**Comment by Annosz** [comment]
Thanks to @VashtiH we have a fix for the issue. I will try zip it up with a few other translation changes and publis it on the weekend.
