### ISSUE TITLE
[Visual Bug]: Completed blacksmith upgrade of Steel Pan has no icon and spams an error message 

### ISSUE THREAD

**Issue by forrester-marc** [Annosz/UIInfoSuite2#560]
### Mod Version

v2.3.4

### Multiplayer

Multiplayer (Host)

### Visual Settings

UI Scale and Zoom 100%

### Steps to Reproduce
1. Upgrade pan to steel
2. Sleep twice

**Comment by forrester-marc** [comment]
### Issue
    Upgrading a pan to steel at the blacksmiths starts with a default watering can icon then becomes blank when it's ready to collect.  Console error repeats several times per second, log file crashes smapi.io

[UI Info Suite 2] This mod failed in the Display.RenderedHud event. Technical details:
NullReferenceException: Object reference not set to an instance of an object.
   at UIInfoSuite2.UIElements.ShowToolUpgradeStatus.OnRenderedHud(Object sender, RenderedHudEventArgs e) in C:\Users\Drew\RiderProjects\DH-UIInfoSuite2\UIInfoSuite2\UIElements\ShowToolUpgradeStatus.cs:line 131
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101

**Comment by drewhoener** [comment]
@forrester-marc Hey there, sorry for the inconvenience! I really need to figure out some sort of throttling for the log messages lol
I've fixed this for the next release. In the meantime, please try this debug build to stop the error spamming :)

[UIInfoSuite2 2.3.4+8577e509.zip](https://github.com/user-attachments/files/15821584/UIInfoSuite2.2.3.4%2B8577e509.zip)

**Comment by forrester-marc** [comment]
Nice one, tysm for the log spam fix.  Icon displaying and console sanity confirmed!
