### ISSUE TITLE
[Breaking]: it worked for a bit but then my game crashed

### ISSUE THREAD

**Issue by TomaetoSauce** [Annosz/UIInfoSuite2#570]
### Mod Version

2.3.4

### Multiplayer

Single Player

### SMAPI Log

i only have a picture of it which is attached below

### Issue

I installed this which took some work until I finally figured it out. Its running with a ton of other mods on Stardew 1.6, using Vortex as a mod manager, and SMAPI 4.08 as the loader. It worked for a couple in game days but then I got distracted from my game and ended up passing out. It was stuck on the black screen with the "saving..." message in the bottom left corner. After a few seconds of waiting, the game crashed entirely and the following log and error message popped up (attached below, ignore the caption). Now, I cant open Stardew because SMAPI loads the mods then just shuts off. I uninstalled the mod and Stardew worked again, but then I reinstalled it and it wouldn't let me open the game. Also, after I closed out the windows error message another appeared mentioning something about UI and memory, but I don't remember what it said. 
### Steps to Reproduce
1. Install mod
2. game crash
3. uninstall
4. reinstall
![image](https://github.com/Annosz/UIInfoSuite2/assets/173313014/76c644cc-8332-4982-a1f6-1969e0a5d26c)

**Comment by drewhoener** [comment]
Hi @TomaetoSauce, this looks like an issue with SpaceCore or another mod you have, UIInfoSuite doesn't mess with saving, so I'm unable to support your issue. 
Additionally, most mod authors recommend not using Vortex, as it can mess with mod functionality. I'd recommend installing your mods manually or using something like Stardrop.
