### ISSUE TITLE
After update to version 2.1.4 townspeople on map are not displayed

### ISSUE THREAD

**Issue by Eliorim** [Annosz/UIInfoSuite2#58]
After update to version 2.1.4 townspeople on map are not displayed. It worked fine before the update.

I tried:
- toggling off/on without effect.
- installing "clean" by deleting old install folder and creating new folder
- installing previous version (2.1.3)

Installing the previous version 2.1.3 solved the issue i.e. previous version works.

Only other mod I have installed is Lookup Anything.
Using SMAPI 3.12.2

**Comment by Annosz** [comment]
I think this is linked to [issue 59](https://github.com/Annosz/UIInfoSuite2/issues/59).

**Comment by Annosz** [comment]
It was solved by @Deflaktor in PR #60.
