### ISSUE TITLE
[Visual Bug]: Upgrading pan not displayed

### ISSUE THREAD

**Issue by Kr0sshair** [Annosz/UIInfoSuite2#580]
### Mod Version

v2.3.4

### Multiplayer

Single Player

### Visual Settings

UI Scale 100%, Zoom: 135%

### SMAPI Log

[UI Info Suite 2] This mod failed in the Display.RenderedHud event. Technical details: NullReferenceException: Object reference not set to an instance of an object.    at UIInfoSuite2.UIElements.ShowToolUpgradeStatus.OnRenderedHud(Object sender, RenderedHudEventArgs e) in C:\Users\Drew\RiderProjects\DH-UIInfoSuite2\UIInfoSuite2\UIElements\ShowToolUpgradeStatus.cs:line 131    at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101

### Steps to Reproduce
1. Make junimos destroy glittering boulder
2. Unlock panning
3. Get copper pan
4. Upgrade pan (any tier - any tier)

At first it was the "steel pan ready in 3 days" with my iridium trash can icon (the last one i upgraded before pan), now i went gold (and now  iridium WIP) it repeats that log i sent, spamming it non stop. Each frame im guessing. UI Info Suite doesnt understand panning.

**Comment by drewhoener** [comment]
@Kr0sshair Please check #560 and #573, sorry I haven't put out a proper fix yet. Been a bit busy with work

**Comment by SteveS8** [comment]
I wouldn't consider this is just a visual bug with SMAPI showing NullReference errors as fast as possible
