### ISSUE TITLE
64 bit compatibility and SMAPI 3.13.0-beta

### ISSUE THREAD

**Issue by teaforjurgen** [Annosz/UIInfoSuite2#59]
Basically, SMAPI has updated to support Stardew's new 64 bit changes and now this mod no longer works. For example, Animals needing petting no longer works, the instant access to the calendar and notice boards no longer appear, furnaces no longer give any information when hovered over, and items no longer have detailed information. Additionally, as mentioned in a previous issue, villager icons no longer work, but this issue remains regardless of whether the latest or second latest release is used. I haven't had the time to run through Pathoschild's SMAPI and Stardew update mod migration guide yet, so I thought I'd leave a message here.

Link to page on updating mods for the new SMAPI and Stardew Updates:
https://stardewvalleywiki.com/Modding:Migrate_to_Stardew_Valley_1.5.5

**Comment by Annosz** [comment]
Another useful link for this issue - [How to set up Stardew Valley 1.5.5 beta]( https://www.patreon.com/posts/55035968)

**Comment by Annosz** [comment]
This was referenced in #65 but I think that's not a complete solution, so I'm reopening it.

**Comment by Deflaktor** [comment]
The pull request #65 fixes what breaks the current build for the beta. It makes the current version forward compatible to 1.5.5.
The pull request #66 should only be merged when 1.5.5 is fully released as it is not backwards compatible to 1.5.4.
