### ISSUE TITLE
[Breaking]:５時間模索したけど初心者にはわからなかった。申し訳ない。

### ISSUE THREAD

**Issue by utatane-nightfox** [Annosz/UIInfoSuite2#595]
### Mod Version

v2.3.4

### Multiplayer

Single Player

### SMAPI Log

https://smapi.io/log/5318e46a04a243fd984161a59ece76f2

### Issue
ゲーム自体は正常に機能する。modが反映されない。

![スクリーンショット 2024-09-01 124454](https://github.com/user-attachments/assets/a39a92f1-0082-42f3-b2ee-567c2f8516e7)
![スクリーンショット 2024-09-01 124619](https://github.com/user-attachments/assets/8a3953ef-90aa-4b17-9f1f-7a71cacb770a)
![スクリーンショット 2024-09-01 125225](https://github.com/user-attachments/assets/b567a7a4-ffcd-470d-a461-4f66fcacc83b)
![スクリーンショット 2024-09-01 125332](https://github.com/user-attachments/assets/ae719688-6d6a-4d1e-ad9c-738918a2ee3c)

### Steps to Reproduce
1. First　　　　　modをDLした後、zipファイルをmodファイルに解凍。
2. Second　　    ゲーム起動後、エラー文が発生。
3. Third　　　　プレイは問題無くできるが、modが反映されない。
4. Fourth　　　 調べてみたが、manifestファイルは存在している。

Cファイルでインストールしなければいけないのでしょうか？

**Comment by JokerBTA** [comment]
I don't think you need the UI Info Suite 2 Master, just UI Info Suite 2.

**Comment by utatane-nightfox** [comment]
https://smapi.io/log/2267dc22930049aeadc33d9461ea866d
UI Info Suite 2 Masterを削除したが変わらず・・・
UI Info Suite 2 Masterはこのサイトからダウンロードしたものです。
UI Info Suite 2と書かれたファイル は、Nexusからダウンロードしたもので、日本語訳版と思われます。
↓
https://www.nexusmods.com/stardewvalley/mods/24756?tab=description

**Comment by wulingxuan** [comment]
![image](https://github.com/user-attachments/assets/fe54b50b-9323-489a-8e03-340803a78b4e)
You should download this, not the source code.

**Comment by utatane-nightfox** [comment]
無事できました！！
ご丁寧にありがとうございました。
