### ISSUE TITLE
[Visual Bug]: New trees not named properly in hover text

### ISSUE THREAD

**Issue by MidnightChord** [Annosz/UIInfoSuite2#601]
### Mod Version

V2.3.4

### Multiplayer

Single Player

### Visual Settings

UI Scale: 75% Zoom: 75%

### SMAPI Log

https://smapi.io/log/aec949d7cb8e407fbbe5af39ed076224

### Issue
![SVE tree issue](https://github.com/user-attachments/assets/932956f5-bfaa-40a2-af57-701b84016bd3)
### Steps to Reproduce
1. Install SVE
2. Install the new Frontier Farm
3. Install UIInfoSuite 2
4. Hover over the newly added Birch and Fir Trees (SVE ver. 1.15)

**Comment by CosmicKillsSouls** [comment]
This is fixed in PR#604 if it gets merged.

**Comment by drewhoener** [comment]
Forgot to close this issue, fixed in v2.3.5
