### ISSUE TITLE
[Visual Bug]: Error entering the interface

### ISSUE THREAD

**Issue by s3713434** [Annosz/UIInfoSuite2#624]
### Mod Version

v2.3.5

### Multiplayer

Single Player

### Visual Settings

UI Scale:100%; UI Zoom:100%

### SMAPI Log

https://smapi.io/log/5ba343999fe84fc3a3d672145544f079

### Steps to Reproduce
1. Load your game
2. Exit to the main
![image](https://github.com/user-attachments/assets/52b62c39-8991-4fc8-a6ae-cfea99fe76e5)

The first time you enter the interface it will not report an error, but after entering the game and then exiting to the main page it will report an error.
Another one is the inability to display options during festivals, I'm not sure if that's due to the mod :(

**Comment by drewhoener** [comment]
Hello! This will be fixed in a release either today or tomorrow, I'm currently finishing the 1.6.9 update :)
