### ISSUE TITLE
[Breaking]: 'UiInfoSuite2 is no longer compatible' even with the newest version

### ISSUE THREAD

**Issue by kxrscrxsh** [Annosz/UIInfoSuite2#633]
### Mod Version

v2.3.6

### Multiplayer

Single Player

### SMAPI Log

https://smapi.io/log/3f78d2dcffdb41d2a321fcdfbeb06633

### Description

Title explains the problem mostly! Even though I have the newest version of the mod downloaded from Nexus, Smapi says that it is no longer compatible. Tried only loading this mod and Smapi, but the problem continued,

**Comment by Hymneer** [comment]
I met the same bug. info: - UI Info Suite 2 2.3.6 because it's no longer compatible. Please check for a new version at https://smapi.io/mods

**Comment by dotarjun** [comment]
Bump

**Comment by casablanca0311** [comment]
I met the same bug.

**Comment by ilolomi** [comment]
Same here, newest update of smapi and ui2

**Comment by TheLambdaEnergy** [comment]
me too , i downloaded it from nexus and github , both cause this error

**Comment by Adireael** [comment]
This error is because of a new patch for Stardew Valley, it f/cked Info UI and NPC location. Hoping the creators can upload it to make them compatible.

**Comment by Farrize** [comment]
[UIInfoSuite2 2.3.6.zip](https://github.com/user-attachments/files/17719529/UIInfoSuite2.2.3.6.zip)

You can use this dll , been working for me till now, we can wait for the author response in the meantime

**Comment by Farrize** [comment]
same issue as
https://github.com/Annosz/UIInfoSuite2/issues/631

**Comment by drewhoener** [comment]
Thank you for the temp fix, I’ll release a new version in a few hours, need
to finish work


-- 
Drew Hoener

**Comment by JC2602-hub** [comment]
The latest SMAPI update fixed the problem

**Comment by drewhoener** [comment]
Fixed in v2.3.7
