### ISSUE TITLE
Changes made in the in-game menu not saving

### ISSUE THREAD

**Issue by JokerBTA** [Annosz/UIInfoSuite2#64]
Everytime I load up the game, the changes I made previously aren't being saved. I have to check or uncheck the settings I want to be saved.

I have version 2.1.5 of UI Info Suite 2

**Comment by Annosz** [comment]
@Deflaktor this could be related to the changes in #55.

**Comment by Deflaktor** [comment]
Hi JokerBTA, 
I was unable to reproduce the issue. Can you send me your save file?
Please note, that the settings are only ever being saved when the game itself saves (i.e. you go to sleep)

**Comment by JokerBTA** [comment]
I just downloaded 2.1.3 as was recommended by some in the Stardew Valley discord server last night. Let me download it and find my save file.

**Comment by JokerBTA** [comment]
Update: After saving, it worked. I closed it and reopened and my settings were saved. I dunno what happen, might've been a glitch. You can go ahead and close it.
