### ISSUE TITLE
File Not Found Exception

### ISSUE THREAD

**Issue by TG-BrainFog** [Annosz/UIInfoSuite2#67]
After upgrading Smapi to the 3.13.0 beta along with the 1.5.5 beta of STV, I started getting a file not found error on launch. I assumed this was my fault (being that I have no idea what I'm doing), so I uninstalled everything, deleted the entire STV folder,  and reinstalled from scratch.  After installing the mod and doing a test run, still got the same result. As I said, I'm pretty clueless as to how any of this works, but I don't know what else to do. I'm seeing other posts regarding issues with the 64 bit updates killing some of the labeling and such, but I'm not getting it to load in the first place. 

Here's the Smapi log:
https://smapi.io/log/2e4bb23297f54597a58962ad8c774b81

**Comment by Deflaktor** [comment]
This has already been fixed with pr #65
please wait for next release
