### ISSUE TITLE
Issue with Version 1.5.5 Beta/3.13.0 Beta

### ISSUE THREAD

**Issue by JokerBTA** [Annosz/UIInfoSuite2#68]
Transitioned from Unofficial 64-bit to the Version 1.5.5 beta, everything loaded up just fine but UI Info Suite 2 came up with an error when I loaded up the save file. When I click on the tab for UI Info Suite 2, it comes up blank.

Here is my log: https://smapi.io/log/073db1804384435893eb8bf6f3c0f38c

**Comment by talunesilius** [comment]
Having  the exact same issue.

**Comment by kik4186** [comment]
https://smapi.io/log/087566f1db7f4e7798b3719074fc9507 also having an issue

**Comment by Annosz** [comment]
@Deflaktor this is the same issue as in #67, and it's fixed in #65, right?

In this case I will create a new release with the changes ASAP, sorry, I did not realize it contained so important bugfixes :)

**Comment by Deflaktor** [comment]
Yep, same issue. Thanks for making new release :)
