### ISSUE TITLE
Error messages in SMAPI when opening the map for the first time

### ISSUE THREAD

**Issue by Annosz** [Annosz/UIInfoSuite2#69]
SMAPI console logs a lot of NullReference exception when we open the map for the first time (maybe only if we open it fst enough after loading a save).

The error is in LocationOfTownfolk.cs: we run Line 282 once, before initializing the _friendNames properties in Line 180. The following executeions are okay, and the first one doesn't break the game either, because the error is handled and logged, but it messes up the console and can scare the player. A null check should be added.

**Comment by Deflaktor** [comment]
Fixed by PR #72
