### ISSUE TITLE
Request: Add Berry Season Icons 

### ISSUE THREAD

**Issue by chocoashlim** [Annosz/UIInfoSuite2#82]
Hello! I was wondering if it's possible to add a salmonberry or blackberry icon on the top right during their respective seasons? 

I saw a mod for adding these icons to the calendar but thought it would be a fantastic addition to this mod with all the other icons next to the journal! 

Also, I already commented this but I just have to say again that I really appreciate everything you do. You are incredible!!!

**Comment by Annosz** [comment]
Great idea!

**Comment by drewhoener** [comment]
I can take this one

**Comment by drewhoener** [comment]
![image](https://user-images.githubusercontent.com/6218989/169663926-5a832197-4169-4814-938c-9fb5005b0f5c.png)
![image](https://user-images.githubusercontent.com/6218989/169663991-2673a45c-668b-432e-84b3-97e39a2e6a84.png)
![image](https://user-images.githubusercontent.com/6218989/169664111-7b7a1f9b-6737-4b4a-bddf-0a3aff1a2350.png)

Added icons for salmonberries, blackberries, and hazelnuts from trees (fall 14-28, I thought it fit the theme)

**Comment by Annosz** [comment]
Thanks @drewhoener for the implementation, your work is always excellent! :)

I like the hazelnut icons too, but I added it as an extra option which the player can enable if he wants. I think it's overwhelming information for the average users, especially as it is active for 14 days: #187 Hazelnut icon changes
