### ISSUE TITLE
Screen goes black with cursor while saving

### ISSUE THREAD

**Issue by shuniichan** [Annosz/UIInfoSuite2#84]
After the daily total income summary, the screen goes black with the cursor still movable, smapi reports errors with Ui info suite 2, I'm using the latest 1.5.5 beta, here's the log: https://smapi.io/log/700379daa0494fabb1960d76c44e0dd0

**Comment by Annosz** [comment]
I think this bug was related to the beta version (at that time this mod did not even support 1.5.5). 

As it was not reported since then, I will close this issue for now, but of course if the issue still persist, feel free to reopen it. I will investigate it if anyone else has this error too :)
