### ISSUE TITLE
Weather icon doesn't appear

### ISSUE THREAD

**Issue by gusbaruc** [Annosz/UIInfoSuite2#92]
Sometimes the Weather icon doesn't appear.
This has occurred to me a few times for both rainy and stormy days. I haven't arrived in winter yet, but it should probably happen with the blizzard days as well.

**Comment by rodrigovda** [comment]
I can confirm this happening to me.

Maybe this has something to do with forced weather not being taken into account by the mod?

**Comment by Annosz** [comment]
Hello! Yes, using a rain totem is likely to cause issues, I don't remember if I have tried that.

I just want to make sure that you know, that the weather icon is a forecast, so it is not displayed on a rainy day, but the day before, and warns you that "it will be raining *tomorrow*". So it's not a bug if it's raining but you cannot see the icon, because it gives information about the next day - the same as the weather forecast in the TV. Sorry if this is obvious, I just want to rule out miscommunication :)

The error is real if you experience that the weather forecast in the TV tells something different from the icon. If this is the case, is there any chance that you can send me a save file from a day like this to iamannosz@gmail.com?

**Comment by rodrigovda** [comment]
I did not mean rain totems, but "forced weather" as in [how it is described in the wiki](https://stardewcommunitywiki.com/Modding:Weather_data#Forced_weather): when the game doesn't "generate" a random weather condition.

The bug that we 

> 
> 
> I just want to make sure that you know, that the weather icon is a forecast, so it is not displayed on a rainy day, but the day before, and warns you that "it will be raining _tomorrow_". So it's not a bug if it's raining but you cannot see the icon, because it gives information about the next day - the same as the weather forecast in the TV. Sorry if this is obvious, I just want to rule out miscommunication :)
> 
> The error is real if you experience that the weather forecast in the TV tells something different from the icon. If this is the case, is there any chance that you can send me a save file from a day like this to [iamannosz@gmail.com](mailto:iamannosz@gmail.com)?

Yes, that is correct, the error is real, the weather forecast in the TV said that it would rain the next day yet the icon didn't show up. And the next day indeed rained. If I find the bug happening again I'll make sure to backup the savefile so I can test around it or share it here, for sure.

**Comment by rodrigovda** [comment]
I think it happened on Summer, so it might have been Summer 13th or Summer 26th (not sure though, I came here to report a more serious issue and came across this bug so I came to give my two cents).

What I can say for sure is that this happened on the first year before Fall (I'm currently on Fall 2nd).

**Comment by gusbaruc** [comment]
I'm aware that the icon is a prediction for the next day, and it really is in trouble. I hadn't tested it with the totem. The problem I had was with normal predictions.

It's happened a couple of times that I turn on a TV, see a rain forecast but it doesn't appear on the icon. I'm not sure what causes this error, but in my last experience I remember that it rained two days in a row. For the first the icon appeared, for the second it didn't.

Just like Rodrigo, next time it happens to me I'll make a backup so you can analyze.

**Comment by rodrigovda** [comment]
Although It's not the same issue, I'm having the opposite happening to me right now: Weather forecast says it will be sunny, but the Icon says thunderstorm.
Attached savefile
[Borderland_293639271.zip](https://github.com/Annosz/UIInfoSuite2/files/7597876/Borderland_293639271.zip)

**Comment by Annosz** [comment]
Thank you guys for the reports and mostly for the save file, it helped me a lot and (hopefully) I found the solution to it :)
