### ISSUE TITLE
Luck Exact Value after Secret Note #20

### ISSUE THREAD

**Issue by skaiteo** [Annosz/UIInfoSuite2#94]
The exact value for luck displayed becomes off by a very small amount, causing many decimal points to be displayed in the Luck icon after completing Secret Note #20, which grants a Special Charm that permanently increases daily luck.

https://stardewvalleywiki.com/Secret_Notes#Secret_Note_.2320

![image](https://user-images.githubusercontent.com/32006116/143667323-dc9013ac-2ab6-494e-97a2-5105895a94fd.png)

**Comment by Annosz** [comment]
Thanks, that really looked bad :)
