### ISSUE TITLE
PT-BR translate

### ISSUE THREAD

**Issue by gusbaruc** [Annosz/UIInfoSuite2#97]
Hi,
I redid the pt-BR translation of this mod. Some lines were untranslated and others were not translated so well (in my opinion). If you want to add it to the project, I'll leave it attached here.
[pt-br.zip](https://github.com/Annosz/UIInfoSuite2/files/7628366/pt-br.zip)

**Comment by Annosz** [comment]
Thanks for your work, I will include it in the next update!
