### ISSUE TITLE
Full Hungarian translate (tested)

### ISSUE THREAD

**Issue by IISzalonnaII** [Annosz/UIInfoSuite2#98]
Hi!

Here is the full Hungarian translation of the mod with the new options and accents! 
[UIInfoSuite2hu.zip](https://github.com/Annosz/UIInfoSuite2/files/7634132/UIInfoSuite2hu.zip)

**Comment by Annosz** [comment]
Thanks for your work, I will include it in the next update!
(Érdekes, hogy kódírás közben odáig sose jutottam el, hogy a magyar fordítást rendesen összerakjam... :) )
