### ISSUE TITLE
TR-tr translation

### ISSUE THREAD

**Issue by RaiSTliNThEOnE** [Annosz/UIInfoSuite2#99]
Hello there,
turkish translation for UIInfoSuite2.
[UIInfoSuite2TR-tr.zip](https://github.com/Annosz/UIInfoSuite2/files/7647159/UIInfoSuite2TR-tr.zip)

**Comment by Annosz** [comment]
Thanks for your work, I will include it in the next update!

**Comment by RaiSTliNThEOnE** [comment]
Hi Annonz,
turksih translation for latest hazelnut and forageables lines.
[UIInfoSuite2TR-tr.zip](https://github.com/Annosz/UIInfoSuite2/files/8963971/UIInfoSuite2TR-tr.zip)
